### ISSUE TITLE
Invalid Boolean

### ISSUE THREAD

**Issue by sud298** [SRvSaha/CoWinVaccineSlotFinder#1]
![image](https://user-images.githubusercontent.com/43141315/117404620-de1d9c80-af27-11eb-9b14-580be64e0183.png)

**Comment by SRvSaha** [comment]
As mentioned in the README file, please check appsettings.json and change the values, it should be self explanatory

**Comment by sud298** [comment]
Hi;

What will go in the bearer token?

**Comment by SRvSaha** [comment]
Take a Look at the ReadMe file, everything is mentioned there.
