### ISSUE TITLE
Update in repo for 15-18 years and booster dose vaccine

### ISSUE THREAD

**Issue by 520rahul** [SRvSaha/CoWinVaccineSlotFinder#108]
Plz update repo for vaccinations of 15-18 years also and for booster dose also

**Comment by SRvSaha** [comment]
@520rahul I don’t think any changes are needed in the code. 

Only configuration to be done properly. Most probably, these will be the changes:

Configuration Should Be "MinAgeLimit": 15, "MaxAgeLimit": 18 in appSettings.json

As per new, as only COVAXIN will be provided so, following can be configured:

Configuration Should Be "VaccineType": "COVAXIN" if you want to get Covaxin

And for booster doses, which are supposed to be given to 60+,

similar changes to be done for “DoseType”, “MinAgeLimit” and “MaxAgeLimit”.

I don’t have the values to mention now, but once it goes live after 10th Jan, we can check out.

**Comment by 520rahul** [comment]
> @520rahul I don’t think any changes are needed in the code.
> 
> Only configuration to be done properly. Most probably, these will be the changes:
> 
> Configuration Should Be "MinAgeLimit": 15, "MaxAgeLimit": 18 in appSettings.json
> 
> As per new, as only COVAXIN will be provided so, following can be configured:
> 
> Configuration Should Be "VaccineType": "COVAXIN" if you want to get Covaxin
> 
> And for booster doses, which are supposed to be given to 60+,
> 
> similar changes to be done for “DoseType”, “MinAgeLimit” and “MaxAgeLimit”.
> 
> I don’t have the values to mention now, but once it goes live after 10th Jan, we can check out.

@SRvSaha thank u so much for considering my request and clearing all doubts. Thanks again

**Comment by 520rahul** [comment]
@SRvSaha when u get time plz check whether repo is working or not. As i tried today with different combinations but repo did not find any slots. But all slots were easily avaible on cowin website. Plz check whether there is any change in api

**Comment by SRvSaha** [comment]
Okay shall check! Can you please do a F12 in browser, go to network section, an then reload cowin search for some pin or district, and share the json response! Also, share your combination for config file by removing confidential data. Since I won’t be able to register for 15-18 years in my profile, need the data for debugging & reverse engineering @520rahul

**Comment by 520rahul** [comment]
Sure @SRvSaha i will share my data

**Comment by 520rahul** [comment]
@SRvSaha today i deleted the old repo and  downlaoded the fresh latest repo and tried to book slot for 15-18 sge group and it booked successfully. Thanks brother. Repo is working perfrctly so i m closing the issue. Thanks again

**Comment by SRvSaha** [comment]
FAQs updated for Reference [FAQs for 15+](https://github.com/SRvSaha/CoWinVaccineSlotFinder#faqs)
