### ISSUE TITLE
Sound for OTP

### ISSUE THREAD

**Issue by anisingh62** [SRvSaha/CoWinVaccineSlotFinder#15]
This could be an addon to this script but the sound should be like OTP required or something very different to the ones in Slot Availability to avoid confusion.

**Comment by SRvSaha** [comment]
Okay that sounds like a good feature! Can you share some sort of tone that you have in mind for OTP? 
Check this library: [`Beep`](https://docs.microsoft.com/en-us/dotnet/api/system.console.beep) and fiddle with the value of frequency and duration to get different kind of tone.

**Comment by SRvSaha** [comment]
@anisingh62 Glad to share that the feature of beeping a sound like "O T P" is being added with commit 53211f4051fa0d423b4a9b91ba12ca5008cc05b0. Have a look, it will be a part of the new Release 2.2.1.

Star the Repo if it helped.

**Comment by SRvSaha** [comment]
Feature Integrated with Release v2.3.0-x86/x64. 
@anisingh62 Give it a try!

**Comment by anisingh62** [comment]
Saurav Sir All working great you a hero. 😄😃

**Comment by SRvSaha** [comment]
@anisingh62 Star the repo! And share your share your feedback here by comment/share/like in the associated [LinkedIn Post](https://www.linkedin.com/feed/update/urn:li:activity:6796093424492720128/). That'll be used as References/Testimonials in the Application and will increase the credibility of the App.
