### ISSUE TITLE
Getting This Error

### ISSUE THREAD

**Issue by jayeshp004** [SRvSaha/CoWinVaccineSlotFinder#18]
![Capture](https://user-images.githubusercontent.com/54260977/118016338-e7b56300-b372-11eb-9005-77c03ee82bfd.JPG)

**Comment by SRvSaha** [comment]
Hi @jayeshp004, Seems like you have not mentioned the the Beneficiaries properly in the JSON File.

Check this:

`"BeneficiaryIds": ["<REPLACE_ME_1>", "REPLACE_ME_2"]` 

> You'll get the beneficiary ID from Step 4. If you have only 1 beneficiary ID then Use it in the <REPLACE_ME_1> section and remove rest eg. ["1111111111111111"]. If you have multiple beneficiaries for which you want to do booking, added them comma separated eg. ["11111111111111", "22222222222222", "33333333333333"]

In case you are still unable to figure out the issue, share this part from appsetting.json

**Comment by jayeshp004** [comment]
"BeneficiaryIds": "20393314886960"

Still Same Problem

**Comment by SRvSaha** [comment]
@jayeshp004 Star and Share the Repo, in case it helped you. Also, would be glad to know if you could successfully book the slot.
