### ISSUE TITLE
Allow Filter to be Done on Vaccination Center Names; Support Filter By Multiple Vaccination Centres

### ISSUE THREAD

**Issue by SRvSaha** [SRvSaha/CoWinVaccineSlotFinder#21]
Usually, in case of cities, searching by PIN or District works fine because of less Geographical Area. However, in case small towns or village, it is pretty difficult just to get slot based on PIN or District as there are scenarios where CVCs (Covid Vaccination Centres) are around 30km apart still share the same PIN Code. In that case, it makes sense to give the User ability to Filter on CVC's Name. 

Name of the CVC can be found from COWIN's Portal:
![image](https://user-images.githubusercontent.com/13312352/118193825-f9c3fe00-b465-11eb-9335-f9f6b631b8da.png)

For Example, in the above scenario, the name of the CVC is  > Apollo Hospital Modern School

**Comment by SRvSaha** [comment]
Feature Added with e503dbc45d2ecdc214c9678785525ab461f69e6d.
@PSuyog97 Please review the change. Shall be integrated in the next release.

**Comment by SRvSaha** [comment]
Changes integrated in Latest Version with Release [v3.0.0](https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v3.0.0)
and deployed, hence closing the Issue

**Comment by jayeshp004** [comment]
can we filter multiple vaccines centers of different pincodes ??
like x in z pincode
y in j pincode
i in o pincode

**Comment by SRvSaha** [comment]
Hi, 

As of now, the feature of searching by Multiple Centre Names is not there.

You can only search for a particular centre within PIN/District.

Adding mapping of Names with PIN would be a bit challenging, but can be done

**Comment by SRvSaha** [comment]
> 
> 
> can we filter multiple vaccines centers of different pincodes ??
> like x in z pincode
> y in j pincode
> i in o pincode

Working on the feature, shall be deployed soon. Shall let you know

**Comment by SRvSaha** [comment]
> 
> 
> can we filter multiple vaccines centers of different pincodes ??
> like x in z pincode
> y in j pincode
> i in o pincode

Hi @jayeshp004 The feature is added and shall be released today with v4.2.0.
