### ISSUE TITLE
Internal Server Error on Schedule Appointment

### ISSUE THREAD

**Issue by deepgandhi** [SRvSaha/CoWinVaccineSlotFinder#22]
Schedule Appointment API gives Internal Server Error. Code 500

Headers are given below:

{'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '2', 'Connection': 'keep-alive', 'Date': 'Fri, 14 May 2021 06:56:39 GMT', 'x-amzn-RequestId': '2e7b1e70-08c6-4049-a482-18862c5ae968', 'X-DNS-Prefetch-Control': 'off', 'X-XSS-Protection': '1; mode=block', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'x-amzn-Remapped-Content-Length': '2', 'X-Frame-Options': 'DENY', 'Access-Control-Allow-Headers': 'Content-Type, Authorization', 'x-amzn-Remapped-Connection': 'keep-alive', 'X-Download-Options': 'noopen', 'x-amz-apigw-id': 'fTnOQFUqhcwFjHw=', 'X-Content-Type-Options': 'nosniff', 'ETag': 'W/"2-vyGp6PvFo4RvsFtPoIWeCReyIC8"', 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS', 'Access-Control-Expose-Headers': 'Version', 'X-Amzn-Trace-Id': 'Root=1-609e1f27-45a214651ac95ecf0839be52', 'x-amzn-Remapped-Date': 'Fri, 14 May 2021 06:56:39 GMT', 'Access-Control-Allow-Credentials': 'true', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 dfa341e087e42ff5ffabf58ef776d65b.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'BOM52-C1', 'X-Amz-Cf-Id': 'sbr2Ibq0LJ1mcQCLfa4lG2Qr_28qjLctyT1AWJghORcJgPpAl-ZfFg=='}

**Comment by SRvSaha** [comment]
Hi @deepgandhi, 5XX Errors are usually from Server Side, there's nothing much I can help you with.
Secondly, I feel this Content Header is not from the Application it's extracted from somewhere else.
I'll check the endpoint from my end, but as earlier mentioned for Server Side Error, I won't be able to help much.

Looking like there is some issue with the Caching Service, CloudFront `'X-Cache': 'Error from cloudfront',`

**Comment by deepgandhi** [comment]
Thank you @SRvSaha

**Comment by SRvSaha** [comment]
It is working from the Application, give it a try! In Case, I could help you, feel free to Star the repo and share it with your buddies! Also share your feedback by comment/share/like in the associated [ LinkedIn Post](https://www.linkedin.com/feed/update/urn:li:activity:6796093424492720128/) That'll be used as References/Testimonials in the Application and will increase the credibility of the App.
