### ISSUE TITLE
Please Give option for clicking Reschedule button

### ISSUE THREAD

**Issue by anisingh62** [SRvSaha/CoWinVaccineSlotFinder#23]
Instead of clicking Schedule...can't it be possible that script could click just reschedule button...if the Beneficiary ID has already registered automatically?

**Comment by SRvSaha** [comment]
Reschedule is not a very important feature as of now! Shall be added once priority developments are over.

**Comment by SRvSaha** [comment]
@anisingh62 Hi, can you please elaborate the workflow of how the re-scheduling feature should work along with scheduling? Need the workflow/flow diagram to see it’s feasibility

**Comment by anisingh62** [comment]
Sir,
I am just a mechanical engineer wanting you to train me and get my career
switch 😅. I really don't know what to do or how to explain the workflow.
