### ISSUE TITLE
API Structure of Get By PIN or District has changed; Segregation is done between Dose Type 1 & Dose Type 2

### ISSUE THREAD

**Issue by SRvSaha** [SRvSaha/CoWinVaccineSlotFinder#25]
**Describe the bug**
The APIs which provide the slots information of Covid Vaccination Centres by PIN or by District has changed the structure to send provide the Availability of Vaccines segregated between Dose Type 1 and Dose Type 2.
Therefore, changes are to be done to fix this as per the Dose Type in the Config File

`"DoseType": 1/2,`

New API Structure:
```json
{
  "centers":[
    {
      "center_id":1234,
      "name":"District General Hostpital",
      "name_l":"",
      "address":"45 M G Road",
      "address_l":"",
      "state_name":"Maharashtra",
      "state_name_l":"",
      "district_name":"Satara",
      "district_name_l":"",
      "block_name":"Jaoli",
      "block_name_l":"",
      "pincode":"413608",
      "lat":28.7,
      "long":77.1,
      "from":"09:00:00",
      "to":"18:00:00",
      "fee_type":"Free",
      "vaccine_fees":[
        {
          "vaccine":"COVISHIELD",
          "fee":"250"
        }
      ],
      "sessions":[
        {
          "session_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "date":"31-05-2021",
          "available_capacity":50,
          "available_capacity_dose1":25,
          "available_capacity_dose2":25,
          "min_age_limit":18,
          "vaccine":"COVISHIELD",
          "slots":[
            "FORENOON",
            "AFTERNOON"
          ]
        }
      ]
    }
  ]
}
```

**Comment by samip404** [comment]
new vaccine type also added on cowin "sputnikV". and today i mark that on cowin web app we are not able to select multiple person. So can we able to book slot still using release version 3.0? I have no programming knowledge.

**Comment by SRvSaha** [comment]
Hi @samip404, you can still use the version 3.0.0 to book, however you might see some inconsistencies in the booking Availability Slot data, due to the changes in the internal API. However, application is still functional and will get will job done.

WIP to fix the issue to release a new version ASAP with fixes to incorporate the changes done in the API

**Comment by SRvSaha** [comment]
@samip404  In Case, I could help you, feel free to Star the repo and share it with your buddies! Also share your feedback by comment/share/like in the associated LinkedIn Post (https://www.linkedin.com/feed/update/urn:li:activity:6796093424492720128/) That'll be used as References/Testimonials in the Application and will increase the credibility of the App.

**Comment by samip404** [comment]
I book my vaccine slot for my family. After 14 days of try  I successfully booked slot for my 4 member family using this software in Surat corporation. Thank you all contributing member. I wish for all your happy, wealthy life. God bless you 🙏

**Comment by SRvSaha** [comment]
> 
> 
> I book my vaccine slot for my family. After 14 days of try I successfully booked slot for my 4 member family using this software in Surat corporation. Thank you all contributing member. I wish for all your happy, wealthy life. God bless you 🙏

@samip404 Awesome! Great to know that. Really very happy that I could help.
Feel free to Star the repo and share it with your buddies! Also share your feedback by comment/share/like in the associated LinkedIn Post (https://www.linkedin.com/feed/update/urn:li:activity:6796093424492720128/) That'll be used as References/Testimonials in the Application and will increase the credibility of the App.

**Comment by Tnu02** [comment]
Hey @SRvSaha i guess cowin site changed the functionality to select multiple beneficiaries at the same time.. Would you prefer adding multiple beneficiaries or just the single..!!

**Comment by SRvSaha** [comment]
> 
> 
> Hey @SRvSaha i guess cowin site changed the functionality to select multiple beneficiaries at the same time.. Would you prefer adding multiple beneficiaries or just the single..!!

Hi @Tnu02, yes I could see some issues related to that. Could you try booking and your booking failed due to Multiple Beneficiaries?
If yes, I can check. Otherwise there is no way to check that.

**Comment by Tnu02** [comment]
> > 
> > 
> > Hey @SRvSaha i guess cowin site changed the functionality to select multiple beneficiaries at the same time.. Would you prefer adding multiple beneficiaries or just the single..!!
> 
> Hi @Tnu02, yes I could see some issues related to that. Could you try booking and your booking failed due to Multiple Beneficiaries?
> If yes, I can check. Otherwise there is no way to check that.

Not yet checked just saw the changes on the site, so thought to tell you..

**Comment by SRvSaha** [comment]
@Tnu02 @samip404 Version 4.0.0 is out now. Thanks for your patience. Check it out: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/latest

**Comment by SRvSaha** [comment]
Feature integrated in v4.0.0 https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/latest @Tnu02 Try out the new one and share your feedback
