### ISSUE TITLE
Slots are already full but still getting captcha

### ISSUE THREAD

**Issue by akshay8043** [SRvSaha/CoWinVaccineSlotFinder#27]
![image](https://user-images.githubusercontent.com/32493756/118396859-12533480-b66f-11eb-924b-dfe61ab2103f.png)

I am trying since 15 minutes and it is still coming up again and again even after slots are full

**Comment by SRvSaha** [comment]
Hi @akshay8043, this is happening because there is some inconsistency in the the `available_capacity` field in the CoWIN API
as mentioned here: https://github.com/cowinapi/developer.cowin/issues/234, https://github.com/cowinapi/developer.cowin/issues/231, https://github.com/cowinapi/developer.cowin/issues/224, https://github.com/cowinapi/developer.cowin/issues/226
They have made changes in the API, so this is happening.

I have made fix of this in the latest commit, changes will be release as a part of v4.0.0 tonight.

Sorry for the inconvenience caused. Also, Captcha Popup was coming since the Available Capacity was shown as 25 which is greater than the Minimum Available Capacity set in Config File.

**Comment by akshay8043** [comment]
@SRvSaha Hi,

I am still getting this message even if you see on website the count is zero.

![image](https://user-images.githubusercontent.com/32493756/118397207-8f32de00-b670-11eb-9f84-f33c96fca02f.png)

![image](https://user-images.githubusercontent.com/32493756/118397225-a671cb80-b670-11eb-8f7c-1cea2f75c0fa.png)

**Comment by SRvSaha** [comment]
Hi @akshay8043, if you just go to F12, Network -> XHR and then refresh the page will will see there is a request to /calenderByDistrict Endpoint.

Just go to the Response of that Request, you'll see that there is 0 available capacity for Dose 1 and available_capacity = 25, that is why you are getting the captcha prompt. Also, in the screenshot, you can see in CoWIN that "Search Results for Dose Type 1", so the Available Capacity of Dose Type 1 `available_capacity_dose1` will be 0 in the repsonse JSON.

This is the latest change that have made in the API, so there is this inconsistency. I have made the fix with commit: 44da53000896975b7a59172851f4e6325309defc and the change will be released with v4.0.0 tonight.

Sorry for the inconvenience caused.

**Comment by akshay8043** [comment]
> Hi @akshay8043, this is happening because there is some inconsistency in the the `available_capacity` field in the CoWIN API
> as mentioned here: [cowinapi/developer.cowin#234](https://github.com/cowinapi/developer.cowin/issues/234), [cowinapi/developer.cowin#231](https://github.com/cowinapi/developer.cowin/issues/231), [cowinapi/developer.cowin#224](https://github.com/cowinapi/developer.cowin/issues/224), [cowinapi/developer.cowin#226](https://github.com/cowinapi/developer.cowin/issues/226)
> They have made changes in the API, so this is happening.
> 
> I have made fix of this in the latest commit, changes will be release as a part of v4.0.0 tonight.
> 
> Sorry for the inconvenience caused. Also, Captcha Popup was coming since the Available Capacity was shown as 25 which is greater than the Minimum Available Capacity set in Config File.

Hey,

Please don't be sorry, I am providing you just a feedback so that more people should not face the issue. Since morning I am trying multiple ways to get these application running.

I have now build new Linux VM for bombardier-gif app.

**Comment by akshay8043** [comment]
> Hi @akshay8043, if you just go to F12, Network -> XHR and then refresh the page will will see there is a request to /calenderByDistrict Endpoint.
> 
> Just go to the Response of that Request, you'll see that there is 0 available capacity for Dose 1 and available_capacity = 25, that is why you are getting the captcha prompt. Also, in the screenshot, you can see in CoWIN that "Search Results for Dose Type 1", so the Available Capacity of Dose Type 1 `available_capacity_dose1` will be 0 in the repsonse JSON.
> 
> This is the latest change that have made in the API, so there is this inconsistency. I have made the fix with commit: [44da530](https://github.com/SRvSaha/CoWinVaccineSlotFinder/commit/44da53000896975b7a59172851f4e6325309defc) and the change will be released with v4.0.0 tonight.
> 
> Sorry for the inconvenience caused.

You are absolutely correct but I got the information from another cowin bot.

![image](https://user-images.githubusercontent.com/32493756/118397556-32d0be00-b672-11eb-99e1-e3f9b8f3678a.png)

**Comment by SRvSaha** [comment]
@akshay8043 Thanks for the feedback. Changes will be deployed and you can try booking the slot using the App tomorrow.

**Comment by JnaneshPrabhu** [comment]
What changes are you doing @SRvSaha ? Will the available_capacity be made equal to available_capacity_dose_1 + dose2?

**Comment by SRvSaha** [comment]
@JnaneshPrabhu No, basically it will detect based on the Dose Type. If the Dose Type of the User is 1, then it will check the `available_capacity_dose1`, else `available_capacity_dose2`

**Comment by JnaneshPrabhu** [comment]
@SRvSaha  But  the public api is still showing wrong data if I am not wrong. Like for instance 201301 is showing same available capacity for 18+ from last 6 hrs I have been observing. How are you circumventing that?

**Comment by SRvSaha** [comment]
> 
> 
> @SRvSaha But the public api is still showing wrong data if I am not wrong. Like for instance 201301 is showing same available capacity for 18+ from last 6 hrs I have been observing. How are you circumventing that?

Hi, @JnaneshPrabhu, Public APIs are cached and hence they may not providing Real-Time Information.

Check the first paragraph here: https://apisetu.gov.in/public/marketplace/api/cowin/cowin-public-v2#/

**Comment by JnaneshPrabhu** [comment]
I am aware about that. But its cached only upto 30 minutes and not hours.. just asking if at all you are aware off it and have a solve for that.

**Comment by SRvSaha** [comment]
> 
> 
> I am aware about that. But its cached only upto 30 minutes and not hours.. just asking if at all you are aware off it and have a solve for that.

Try hitting from multiple machines having Different IP Addresses. In general there a rate limit of 100 requests per 5 minute. So you need to arrange for sufficient machines with different IPs so that you can check for different different PIN/Districts without the throttling.

**Comment by akshay8043** [comment]
@SRvSaha if this API shows cached data, then how are we gonna book a slot if the data is old?
I saw a WhatsApp msg saying that this it has 30 min delay which I initially didn't believe as it was a WhatsApp msg.

![image](https://user-images.githubusercontent.com/32493756/118431994-23468900-b6f5-11eb-8d99-03e75f751806.png)

But you that @JnaneshPrabhu is saying that it's cached with data up to 30 mins. 

How do we assure that we are getting current data?

What can be done to get improve your app?

**Comment by SRvSaha** [comment]
@akshay8043 We aren't using Public API so we will not face the issue of caching. It's a Real-Time system.

**Comment by SRvSaha** [comment]
@akshay8043 @JnaneshPrabhu  Version 4.0.0 is out now. Thanks for your patience. Check it out: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/latest

**Comment by SRvSaha** [comment]
Feature integrated in v4.0.0 https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/latest it should fix the issue.

@akshay8043 Check and share your feedback.
