### ISSUE TITLE
Auto Captcha Reading Functionality

### ISSUE THREAD

**Issue by Rajat-dey** [SRvSaha/CoWinVaccineSlotFinder#36]
You can add an HTML parser to get the captcha when you show it at the popup. For Auto Booking, reference added below.

https://github-dotcom.gateway.web.tr/truroshan/CoWin-Termux

**Comment by SRvSaha** [comment]
@Rajat-dey That's quite interesting. I will check it out. Meanwhile can you see if you can work on the issue?

**Comment by Rajat-dey** [comment]
If I get the bandwidth from the work. I will definitely give it a look. As this feature will increase the possibility of booking to a great extend.

**Comment by Rajat-dey** [comment]
Seems found one good solution, but need to implement it on your app with C#. kindly check this:
https://github.com/anoop142/cowin-cli/blob/main/cowin/captcha.go
https://github.com/ayushchd/cowin_js_bot

I have used the plugin and script, auto captcha works perfectly.

**Comment by SRvSaha** [comment]
Awesome @Rajat-dey, check check it out.
Currently a bit busy with deployment of Milestore v4.0.0

**Comment by Rajat-dey** [comment]
No issue, most of the people are waiting for the v4.0.0.0. As current version will not work most of the time. As the API structure is changed. Kindly deployed it in the Release version.

**Comment by SRvSaha** [comment]
Version 4.0.0 is out now. Thanks for your patience. Check it out: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/latest
@Rajat-dey

**Comment by SRvSaha** [comment]
> 
> 
> Seems found one good solution, but need to implement it on your app with C#. kindly check this:
> https://github.com/anoop142/cowin-cli/blob/main/cowin/captcha.go
> https://github.com/ayushchd/cowin_js_bot
> 
> I have used the plugin and script, auto captcha works perfectly.

Amazing, This looks promising, Shall implement it and release in v4.1.0

**Comment by Tnu02** [comment]
Please implement asap.. Much needed.. 😀

**Comment by SRvSaha** [comment]
@Rajat-dey Thanks for your help, Release [v4.1.0 ](https://github.com/srvsaha/CoWINVaccineSlotFinder/releases/latest) is now  live, with the milestone of AutoCaptcha Feature!
Check it out and share you feedback.

**Comment by Rajat-dey** [comment]
Great to see your response, as I believe it will help lots of users who are just beginners and have little knowledge. Little contribution is good as I have used the app too for slot booking of my family members. So, just wanted to add the feature of auto captcha to contribute from my side. As your code is in C#, therefore I asked you to implement it. Thanks for doing so.

Will definitely use it and will give you feedback in real scenarios. Kudos to You @SRvSaha !!

**Comment by SRvSaha** [comment]
@Rajat-dey  Can you please test the scenario as per the description in #79 for machine and see if it works. Need some feedback that it works, before making a new release. See the discussions for all different types of test scenarios. Would be happy if you can contribute.
