### ISSUE TITLE
Change is session schema

### ISSUE THREAD

**Issue by deepgandhi** [SRvSaha/CoWinVaccineSlotFinder#37]
There is a change in the schema for sessions available. Now there is 2 different availability for dose 1 and dose 2. So, it is required to check the availability of the dose required by the user. currently, it is asking for a captcha even if there is no availability of dose 1 and then throws an error the booking is full. 

 "sessions": [
        {
          "session_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "date": "31-05-2021",
          "available_capacity": 50,
          "available_capacity_dose1": 25,
          "available_capacity_dose2": 25,
          "min_age_limit": 18,
          "vaccine": "COVISHIELD",
          "slots": [
            "FORENOON",
            "AFTERNOON"
          ]

**Comment by SRvSaha** [comment]
Hi @deepgandhi, thanks the feedback. Changes are done to fix the issue.
Related: #25 #27

Changes will be released today with version v4.0.0

**Comment by deepgandhi** [comment]
> Hi @deepgandhi, thanks the feedback. Changes are done to fix the issue.
> Related: #25 #27
> 
> Changes will be released today with version v4.0.0

Okay thank.

**Comment by SRvSaha** [comment]
Hi @deepgandhi, Version 4.0.0 is out now. Thanks for your patience. Check it out: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/latest

**Comment by deepgandhi** [comment]
> Hi @deepgandhi, Version 4.0.0 is out now. Thanks for your patience. Check it out: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/latest

Checked it, it's working fine.

**Comment by SRvSaha** [comment]
@deepgandhi  Can you please test the scenario as per the description in #79 for machine and see if it works. Need some feedback that it works, before making a new release. See the discussions for all different types of test scenarios. Would be happy if you can contribute.

**Comment by deepgandhi** [comment]
> @deepgandhi  Can you please test the scenario as per the description in #79 for machine and see if it works. Need some feedback that it works, before making a new release. See the discussions for all different types of test scenarios. Would be happy if you can contribute.

I will look into it.
