### ISSUE TITLE
unable to book slot, keep getting captcha but not taking it..

### ISSUE THREAD

**Issue by Tnu02** [SRvSaha/CoWinVaccineSlotFinder#38]
Adding screenshot for the same.
![not booking](https://user-images.githubusercontent.com/83922100/118528234-ba482b00-b75f-11eb-9028-e2b06b1e77a5.jpg)

**Comment by SRvSaha** [comment]
@Tnu02 Seems like there is some issue at CoWIN's side, they are unable to process the request and hence sending the reponse of Internal Server Error.

**Comment by Tnu02** [comment]
> @Tnu02 Seems like there is some issue at CoWIN's side, they are unable to process the request and hence sending the reponse of Internal Server Error. Captcha is being prompted since there are free slots available.
> 

I tried booking manually for the same slit and booking happened.. Is there any issue with the 4.0!??

**Comment by akshay8043** [comment]
Yes, this is working.
https://github.com/ayushchd/cowin_js_bot

@SRvSaha Do you know if 1st dose 0 slots available and 2nd dose 100 slots available, will the script go on loop if I want to get the 1st dose?

Like yesterday's issue? I was getting prompt to book a slot but I had not received 1st dose and available slots were for 2nd dose. So do you think this is also resolved?

**Comment by SRvSaha** [comment]
> > @Tnu02 Seems like there is some issue at CoWIN's side, they are unable to process the request and hence sending the reponse of Internal Server Error. Captcha is being prompted since there are free slots available.
> 
> I tried booking manually for the same slit and booking happened.. Is there any issue with the 4.0!??

That’s a big issue:( Problem is that I can’t simulate the same in debug mode. Actually earlier they used the column available_capacity as in v3.0.0 to do check slot availability and do booking.

Due to changes in the API, they have introduced dose wise capacity and were supposed to read from that. They do that when you loginand see the dashboard. However, while proceeding for booking, are they considering both dosewise and total, or just dosewise isthe main concern here. @Tnu02 

@akshay8043 No script should not prompt captcha when you have selected dose type 1 in config and available capacity of dose 1 is zero, even if the capacity of dose 2 is non zero. However, whether they are decreasing the counts of booked slots from respective dose types or from total or both is the reason I feel for the issue.

I would need your help with the reponse JSON from the portal. Can check the same in debug mode and see what’s going wrong. But yes Internal server error is because of inablity to handle at server side.

Still together we need to fix the bug and launch v4.0.1 today itself. Need your help

**Comment by Tnu02** [comment]
@SRvSaha I tried to book just with the single dose slot ie just dose 1, there was not option for slot 2 when i tried manually. 

Let me know how can I help you to fix that bug.

**Comment by SRvSaha** [comment]
> 
> 
> @SRvSaha I tried to book just with the single dose slot ie just dose 1, there was not option for slot 2 when i tried manually.
> 
> Let me know how can I help you to fix that bug.

@Tnu02, I need these Respose raw JSON you get when you are trying to do booking, you can get it from F12 -> Network -> XHR. That'll help in identificaiton

**Comment by Tnu02** [comment]
> > @SRvSaha I tried to book just with the single dose slot ie just dose 1, there was not option for slot 2 when i tried manually.
> > Let me know how can I help you to fix that bug.
> 
> @Tnu02, I need these Respose raw JSON you get when you are trying to do booking, you can get it from F12 -> Network -> XHR. That'll help in identificaiton

From manual booking right !!

**Comment by SRvSaha** [comment]
> 
> 
> > > @SRvSaha I tried to book just with the single dose slot ie just dose 1, there was not option for slot 2 when i tried manually.
> > > Let me know how can I help you to fix that bug.
> > 
> > 
> > @Tnu02, I need these Respose raw JSON you get when you are trying to do booking, you can get it from F12 -> Network -> XHR. That'll help in identificaiton
> 
> From manual booking right !!

Yeah! like this: 
![image](https://user-images.githubusercontent.com/13312352/118594776-9ae4e880-b7c7-11eb-94bb-d6561ac07686.png)

**Comment by SRvSaha** [comment]
@Tnu02 Check the discussion here: https://github.com/bombardier-gif/covid-vaccine-booking/issues/165, is your scenario similiar to this.

**Comment by Tnu02** [comment]
> > > > @SRvSaha I tried to book just with the single dose slot ie just dose 1, there was not option for slot 2 when i tried manually.
> > > > Let me know how can I help you to fix that bug.
> > > 
> > > 
> > > @Tnu02, I need these Respose raw JSON you get when you are trying to do booking, you can get it from F12 -> Network -> XHR. That'll help in identificaiton
> > 
> > 
> > From manual booking right !!
> 
> Yeah! like this:
> ![image](https://user-images.githubusercontent.com/13312352/118594776-9ae4e880-b7c7-11eb-94bb-d6561ac07686.png)

I can't see JSON filter to my console...

**Comment by Tnu02** [comment]
> @Tnu02 Check the discussion here: [bombardier-gif/covid-vaccine-booking#165](https://github.com/bombardier-gif/covid-vaccine-booking/issues/165), is your scenario similiar to this.

I think its kind of similar error.. getting after entering catpcha...

**Comment by SRvSaha** [comment]
@Tnu02 Check this discussion as well: https://github.com/bombardier-gif/covid-vaccine-booking/issues/202
Let me know when you were trying to book, did you already have session booked from Portal and then trying with the App?

**Comment by SRvSaha** [comment]
> 
> 
> > > > > @SRvSaha I tried to book just with the single dose slot ie just dose 1, there was not option for slot 2 when i tried manually.
> > > > > Let me know how can I help you to fix that bug.
> > > > 
> > > > 
> > > > @Tnu02, I need these Respose raw JSON you get when you are trying to do booking, you can get it from F12 -> Network -> XHR. That'll help in identificaiton
> > > 
> > > 
> > > From manual booking right !!
> > 
> > 
> > Yeah! like this:
> > ![image](https://user-images.githubusercontent.com/13312352/118594776-9ae4e880-b7c7-11eb-94bb-d6561ac07686.png)
> 
> I can't see JSON filter to my console...

It's a feature in Firefox, just provide the response even if you don't have firefox

**Comment by Tnu02** [comment]
> @Tnu02 Check this discussion as well: [bombardier-gif/covid-vaccine-booking#202](https://github.com/bombardier-gif/covid-vaccine-booking/issues/202)
> Let me know when you were trying to book, did you already have session booked from Portal and then trying with the App?

Nope... First I tried to book thru app and after the captcha failure i thought to give a manual try and in that i got succeeded.

**Comment by Tnu02** [comment]
> > > > > > @SRvSaha I tried to book just with the single dose slot ie just dose 1, there was not option for slot 2 when i tried manually.
> > > > > > Let me know how can I help you to fix that bug.
> > > > > 
> > > > > 
> > > > > @Tnu02, I need these Respose raw JSON you get when you are trying to do booking, you can get it from F12 -> Network -> XHR. That'll help in identificaiton
> > > > 
> > > > 
> > > > From manual booking right !!
> > > 
> > > 
> > > Yeah! like this:
> > > ![image](https://user-images.githubusercontent.com/13312352/118594776-9ae4e880-b7c7-11eb-94bb-d6561ac07686.png)
> > 
> > 
> > I can't see JSON filter to my console...
> 
> It's a feature in Firefox, just provide the response even if you don't have firefox


Disable Cache
6 requests
38.89 KB / 13.77 KB transferred
Finish: 13.35 s
	
centers	[ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
0	Object { center_id: 563621, name: "Adarsh MiddleSchool KTOR 18-44", address: "Katoria", … }
center_id	563621
name	"Adarsh MiddleSchool KTOR 18-44"
address	"Katoria"
state_name	"Bihar"
district_name	"Banka"
block_name	"Katoriya"
pincode	813106
lat	24
long	86
from	"09:00:00"
to	"17:00:00"
fee_type	"Free"
sessions	[ {…} ]
1	Object { center_id: 280053, name: "High School Dhoraiya18-44", address: "Dhoraiya", … }
center_id	280053
name	"High School Dhoraiya18-44"
address	"Dhoraiya"
state_name	"Bihar"
district_name	"Banka"
block_name	"Dhoraiya"
pincode	813224
lat	24
long	87
from	"09:00:00"
to	"17:00:00"
fee_type	"Free"
sessions	[ {…} ]
2	Object { center_id: 513347, name: "OLD PHC Building Chandan", address: "Chandan PHC", … }
center_id	513347
name	"OLD PHC Building Chandan"
address	"Chandan PHC"
state_name	"Bihar"
district_name	"Banka"
block_name	"Chandan"
pincode	814131
lat	24
long	86
from	"10:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
3	Object { center_id: 615997, name: "HWC Teliya", address: "Fullidumar", … }
center_id	615997
name	"HWC Teliya"
address	"Fullidumar"
state_name	"Bihar"
district_name	"Banka"
block_name	"Fullidumar"
pincode	813102
lat	25
long	86
from	"09:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
4	Object { center_id: 571586, name: "Adarsh HIGH School Amarpur", address: "Amarpur", … }
center_id	571586
name	"Adarsh HIGH School Amarpur"
address	"Amarpur"
state_name	"Bihar"
district_name	"Banka"
block_name	"Amarpur"
pincode	813101
lat	25
long	86
from	"09:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
5	Object { center_id: 563455, name: "High School Block Office 18-44", address: "Belhar", … }
center_id	563455
name	"High School Block Office 18-44"
address	"Belhar"
state_name	"Bihar"
district_name	"Banka"
block_name	"Belhar"
pincode	813202
lat	24
long	87
from	"09:00:00"
to	"18:00:00"
fee_type	"Free"
sessions	[ {…} ]
6	Object { center_id: 612381, name: "OLD Hospital Baunsi 18-44", address: "Baunsi", … }
center_id	612381
name	"OLD Hospital Baunsi 18-44"
address	"Baunsi"
state_name	"Bihar"
district_name	"Banka"
block_name	"Baunsi"
pincode	813104
lat	24
long	87
from	"09:00:00"
to	"17:00:00"
fee_type	"Free"
sessions	[ {…} ]
7	Object { center_id: 513349, name: "Fullidumar Block Sabhaagaar", address: "Fullidumar PHC", … }
center_id	513349
name	"Fullidumar Block Sabhaagaar"
address	"Fullidumar PHC"
state_name	"Bihar"
district_name	"Banka"
block_name	"Fullidumar"
pincode	813207
lat	24
long	86
from	"10:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
8	Object { center_id: 513344, name: "Barahat Block Sabhaagaar", address: "Barahat PHC", … }
center_id	513344
name	"Barahat Block Sabhaagaar"
address	"Barahat PHC"
state_name	"Bihar"
district_name	"Banka"
block_name	"Barahat"
pincode	813103
lat	24
long	87
from	"09:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
9	Object { center_id: 595310, name: "OLD PHC Bulding Chandan18-44", address: "Chandan PHC", … }
center_id	595310
name	"OLD PHC Bulding Chandan18-44"
address	"Chandan PHC"
state_name	"Bihar"
district_name	"Banka"
block_name	"Chandan"
pincode	814131
lat	24
long	86
from	"09:00:00"
to	"17:00:00"
fee_type	"Free"
sessions	[ {…} ]
10	Object { center_id: 576711, name: "FullidumarBlockSabhaagaar18-44", address: "Fullidumar", … }
center_id	576711
name	"FullidumarBlockSabhaagaar18-44"
address	"Fullidumar"
state_name	"Bihar"
district_name	"Banka"
block_name	"Fullidumar"
pincode	813207
lat	24
long	86
from	"09:00:00"
to	"17:00:00"
fee_type	"Free"
sessions	[ {…} ]
11	Object { center_id: 513351, name: "PrimarySchool BaalBhartiRajoun", address: "Rajoun PHC", … }
center_id	513351
name	"PrimarySchool BaalBhartiRajoun"
address	"Rajoun PHC"
state_name	"Bihar"
district_name	"Banka"
block_name	"Rajoun"
pincode	813107
lat	24
long	86
from	"09:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
12	Object { center_id: 256228, name: "HWC PANJWARA", address: "HWC PANJWARA Barahat", … }
center_id	256228
name	"HWC PANJWARA"
address	"HWC PANJWARA Barahat"
state_name	"Bihar"
district_name	"Banka"
block_name	"Barahat"
pincode	813103
lat	24
long	87
from	"09:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
13	Object { center_id: 616026, name: "HWC Singheshwari", address: "Singheshwari", … }
center_id	616026
name	"HWC Singheshwari"
address	"Singheshwari"
state_name	"Bihar"
district_name	"Banka"
block_name	"Baunsi"
pincode	813104
lat	24
long	87
from	"10:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
14	Object { center_id: 281633, name: "HWC Khesar", address: "HWC Khesar", … }
center_id	281633
name	"HWC Khesar"
address	"HWC Khesar"
state_name	"Bihar"
district_name	"Banka"
block_name	"Fullidumar"
pincode	813207
lat	0
long	0
from	"09:00:00"
to	"18:00:00"
fee_type	"Free"
sessions	[ {…} ]
15	Object { center_id: 585566, name: "OLD HOSPITAL PARA MEDICALBANKA", address: "OLD HOSPITAL PARA MEDICAL GANDHI CHOUK", … }
center_id	585566
name	"OLD HOSPITAL PARA MEDICALBANKA"
address	"OLD HOSPITAL PARA MEDICAL GANDHI CHOUK"
state_name	"Bihar"
district_name	"Banka"
block_name	"Banka"
pincode	813102
lat	25
long	86
from	"09:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
16	Object { center_id: 586689, name: "PHC Banka Block 18-44", address: "Banka Sadar PHC Banka", … }
center_id	586689
name	"PHC Banka Block 18-44"
address	"Banka Sadar PHC Banka"
state_name	"Bihar"
district_name	"Banka"
block_name	"Banka"
pincode	813102
lat	24
long	86
from	"09:00:00"
to	"17:00:00"
fee_type	"Free"
sessions	[ {…} ]
17	Object { center_id: 256227, name: "HWC KHARAHARA", address: "HWC KHARAHARA Barahat", … }
center_id	256227
name	"HWC KHARAHARA"
address	"HWC KHARAHARA Barahat"
state_name	"Bihar"
district_name	"Banka"
block_name	"Barahat"
pincode	813103
lat	24
long	87
from	"09:00:00"
to	"18:00:00"
fee_type	"Free"
sessions	[ {…} ]
18	Object { center_id: 279324, name: "HWC Dhouri", address: "Belhar", … }
center_id	279324
name	"HWC Dhouri"
address	"Belhar"
state_name	"Bihar"
district_name	"Banka"
block_name	"Belhar"
pincode	813202
lat	24
long	86
from	"10:30:00"
to	"16:30:00"
fee_type	"Free"
sessions	[ {…} ]
19	Object { center_id: 513345, name: "HighSchool Belhar Block Office", address: "Belhar PHC", … }
center_id	513345
name	"HighSchool Belhar Block Office"
address	"Belhar PHC"
state_name	"Bihar"
district_name	"Banka"
block_name	"Belhar"
pincode	813202
lat	24
long	86
from	"10:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
20	Object { center_id: 582055, name: "P SchoolBaalBhartiRajoun 18-44", address: "RAJOUN", … }
center_id	582055
name	"P SchoolBaalBhartiRajoun 18-44"
address	"RAJOUN"
state_name	"Bihar"
district_name	"Banka"
block_name	"Rajoun"
pincode	813107
lat	24
long	86
from	"09:00:00"
to	"17:00:00"
fee_type	"Free"
sessions	[ {…} ]
21	Object { center_id: 278496, name: "HWC Gokula", address: "Gokula", … }
center_id	278496
name	"HWC Gokula"
address	"Gokula"
state_name	"Bihar"
district_name	"Banka"
block_name	"Baunsi"
pincode	813104
lat	24
long	86
from	"10:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
22	Object { center_id: 616017, name: "HWC JAIPUR", address: "JAIPUR KATORIA", … }
center_id	616017
name	"HWC JAIPUR"
address	"JAIPUR KATORIA"
state_name	"Bihar"
district_name	"Banka"
block_name	"Katoriya"
pincode	813106
lat	24
long	86
from	"09:00:00"
to	"18:00:00"
fee_type	"Free"
sessions	[ {…} ]
23	Object { center_id: 702873, name: "Banka PHC Block A", address: "Banka PHC Block A", … }
center_id	702873
name	"Banka PHC Block A"
address	"Banka PHC Block A"
state_name	"Bihar"
district_name	"Banka"
block_name	"Banka"
pincode	813102
lat	24
long	86
from	"09:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
24	Object { center_id: 513350, name: "Middle School Katoriya", address: "Katoriya RH", … }
center_id	513350
name	"Middle School Katoriya"
address	"Katoriya RH"
state_name	"Bihar"
district_name	"Banka"
block_name	"Katoriya"
pincode	813106
lat	24
long	86
from	"10:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
25	Object { center_id: 513348, name: "High School Dhoraiya", address: "Dhoraiya PHC", … }
center_id	513348
name	"High School Dhoraiya"
address	"Dhoraiya PHC"
state_name	"Bihar"
district_name	"Banka"
block_name	"Dhoraiya"
pincode	813224
lat	24
long	87
from	"10:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
26	Object { center_id: 612436, name: "Barahat SabhaagaarBarahat18-44", address: "Barahat PHC", … }
center_id	612436
name	"Barahat SabhaagaarBarahat18-44"
address	"Barahat PHC"
state_name	"Bihar"
district_name	"Banka"
block_name	"Barahat"
pincode	813103
lat	24
long	87
from	"09:00:00"
to	"17:00:00"
fee_type	"Free"
sessions	[ {…} ]
27	Object { center_id: 280579, name: "HWC Suiya", address: "Suiya", … }
center_id	280579
name	"HWC Suiya"
address	"Suiya"
state_name	"Bihar"
district_name	"Banka"
block_name	"Chandan"
pincode	813106
lat	24
long	86
from	"09:00:00"
to	"18:00:00"
fee_type	"Free"
sessions	[ {…} ]
28	Object { center_id: 513346, name: "OLD Hospital Baunsi", address: "Baunsi PHC", … }
center_id	513346
name	"OLD Hospital Baunsi"
address	"Baunsi PHC"
state_name	"Bihar"
district_name	"Banka"
block_name	"Baunsi"
pincode	813104
lat	24
long	87
from	"10:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
29	Object { center_id: 513352, name: "Pri School Kaurma Shambhugang", address: "Shambhuganj PHC", … }
center_id	513352
name	"Pri School Kaurma Shambhugang"
address	"Shambhuganj PHC"
state_name	"Bihar"
district_name	"Banka"
block_name	"Shambhuganj"
pincode	813211
lat	25
long	86
from	"09:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
30	Object { center_id: 572584, name: "Primary School Kaurma 18-44", address: "Shambhuganj", … }
center_id	572584
name	"Primary School Kaurma 18-44"
address	"Shambhuganj"
state_name	"Bihar"
district_name	"Banka"
block_name	"Shambhuganj"
pincode	813211
lat	25
long	86
from	"09:00:00"
to	"17:00:00"
fee_type	"Free"
sessions	[ {…} ]
31	Object { center_id: 216865, name: "GNM School Administrative Blok", address: "Sadar Hospital Banka", … }
center_id	216865
name	"GNM School Administrative Blok"
address	"Sadar Hospital Banka"
state_name	"Bihar"
district_name	"Banka"
block_name	"Banka"
pincode	813102
lat	25
long	86
from	"09:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
32	Object { center_id: 563355, name: "GNMSchool Administrative 18-44", address: "GNM School Administrative Block Banka", … }
center_id	563355
name	"GNMSchool Administrative 18-44"
address	"GNM School Administrative Block Banka"
state_name	"Bihar"
district_name	"Banka"
block_name	"Banka"
pincode	813102
lat	24
long	86
from	"10:00:00"
to	"17:00:00"
fee_type	"Free"
sessions	[ {…} ]
33	Object { center_id: 576509, name: "AadershHIGH SchoolAmarpur18-44", address: "Amarpur", … }
center_id	576509
name	"AadershHIGH SchoolAmarpur18-44"
address	"Amarpur"
state_name	"Bihar"
district_name	"Banka"
block_name	"Amarpur"
pincode	813101
lat	25
long	86
from	"09:00:00"
to	"17:00:00"
fee_type	"Free"
sessions	[ {…} ]
34	Object { center_id: 320213, name: "HWC Nawada", address: "Nawada Rajoun", … }
center_id	320213
name	"HWC Nawada"
address	"Nawada Rajoun"
state_name	"Bihar"
district_name	"Banka"
block_name	"Rajoun"
pincode	813107
lat	25
long	87
from	"09:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
35	Object { center_id: 255796, name: "HWC Kaushalpur", address: "Koushalpur", … }
center_id	255796
name	"HWC Kaushalpur"
address	"Koushalpur"
state_name	"Bihar"
district_name	"Banka"
block_name	"Amarpur"
pincode	813101
lat	25
long	86
from	"09:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]
36	Object { center_id: 279323, name: "HWC Basmatta", address: "Belhar", … }
center_id	279323
name	"HWC Basmatta"
address	"Belhar"
state_name	"Bihar"
district_name	"Banka"
block_name	"Belhar"
pincode	813202
lat	24
long	86
from	"10:00:00"
to	"16:00:00"
fee_type	"Free"
sessions	[ {…} ]

**Comment by Tnu02** [comment]
@SRvSaha Added above please check..

**Comment by SRvSaha** [comment]
Sessions object is missing, I need that. Also, after successfully booking using Manual Mode, did you try again using App to book?

**Comment by Tnu02** [comment]
> Sessions object is missing, I need that. Also, after successfully booking using Manual Mode, did you try again using App to book?

Nope, didn't try that and not even now. Will check again using the App and will let you know..

**Comment by SRvSaha** [comment]
> 
> 
> > Sessions object is missing, I need that. Also, after successfully booking using Manual Mode, did you try again using App to book?
> 
> Nope, didn't try that and not even now. Will check again using the App and will let you know..

Ideally, if the above mentioned issues are correct, you might get 500 if you try to book again. Not sure, earlier it used to show with 400 bad request.

**Comment by Tnu02** [comment]
Hey @SRvSaha Able to book slot using the App.

But for some reason I keep on getting the available slots on loop, without even booking it constinusly started showing slots.

Attaching the image.

![Image 057](https://user-images.githubusercontent.com/83922100/118630726-6f282980-b7ec-11eb-9973-edbcd1ac69dd.jpg)

**Comment by SRvSaha** [comment]
@Tnu02 That's strange. Do the same thing from browser once. I will also check the same

**Comment by SRvSaha** [comment]
Fixed the Issue with Commit: fb3c37add30a2bc2b92058766d1931210c4e362e

**Comment by SRvSaha** [comment]
Release [v4.1.0 ](https://github.com/srvsaha/CoWINVaccineSlotFinder/releases/latest) is now  live, with the milestone of AutoCaptcha Feature!
Check it out 
@akshay8043
