### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by Pallavi1232** [SRvSaha/CoWinVaccineSlotFinder#39]
1. What values should I enter in min max age for 60+ age group
2. When I am starting the application, it is stopping after reaching approx 500 iterations; although the iteration count is set to 10000

**Comment by SRvSaha** [comment]
Hi @Pallavi1232, you can keep Min as 45 and Max as 100.
Application stopping is a bit strange. Is it like application automatically get crashed and you have start again, so is it like application is stuck up after 500 iterations; I have tried with 1500+ iterations, it worked for me.

If application is crashing, then please provide Event Viewer Logs.

I'm attaching some screenshots how to get the event viewer logs:

> How to do that?
> 
> Go to Event Viewer
> ![image](https://user-images.githubusercontent.com/13312352/118364821-af529680-b5b7-11eb-8982-ca231bf6fc1f.png)
> 
> And then Under Windows Logs, go to Application.
> 
> ![image](https://user-images.githubusercontent.com/13312352/118364835-c2fdfd00-b5b7-11eb-92b4-974c5133d7fa.png)
> 
> After that on the right side, there is a filter current log, filter the Event Sources for .NET Runtime
> ![image](https://user-images.githubusercontent.com/13312352/118364852-df019e80-b5b7-11eb-8ef7-e3d2cfb897af.png)
> 
> Once that is done, you will see the error logs. Share the details like this from there, which will have all the information regarding the crash if that has happened due to some bug in the code or some unexpected behaviour.
> 
> ![image](https://user-images.githubusercontent.com/13312352/118364889-fa6ca980-b5b7-11eb-8c1b-045a643b7da1.png)
>

**Comment by Pallavi1232** [comment]
Sure. It did not get stopped lately.
One more query, can reschedule appointments be booked by the application?
For me those beneficiary ids which are reschedule type are not getting picked up, application says beneficiary id is not valid.

**Comment by Pallavi1232** [comment]
Thanks for the prompt response

**Comment by SRvSaha** [comment]
Hi @Pallavi1232 currently the reschedule feature is not implemented. Request you to go the Cowin Portal and cancel the appointment and then retry from application, it should work.

Also, in Case, I could help you, feel free to Star the repo and share it with your buddies! Also share your feedback by comment/share/like in the associated LinkedIn Post (https://www.linkedin.com/feed/update/urn:li:activity:6796093424492720128/) That'll be used as References/Testimonials in the Application and will increase the credibility of the App.

**Comment by SRvSaha** [comment]
Hi @Pallavi1232 if your issue is resolved feel free to Star the repo so that it appears easily in search results.
Also, you may close the issue.
