### ISSUE TITLE
Issue with Slot Checking Logic, due to which searching works and captcha is prompted, but booking fails

### ISSUE THREAD

**Issue by Tnu02** [SRvSaha/CoWinVaccineSlotFinder#40]
@SRvSaha Can I run multiple instances of the app for different beneficiaries at the same time from one machine..!??

**Comment by SRvSaha** [comment]
@Tnu02 Yes you can. Make sure you create different different copies of folder to run multiple versions of the app

**Comment by Tnu02** [comment]
I tried booking using the app and no luck.. Everytime slot not availabe 😅😅 entered 20-30 captcha..

**Comment by SRvSaha** [comment]
@Tnu02 Unfortunately that's not in my hand!

**Comment by SRvSaha** [comment]
Release [v4.1.0 ](https://github.com/srvsaha/CoWINVaccineSlotFinder/releases/latest) is now  live, with the milestone of AutoCaptcha Feature!
Check it whether you are still facing the same issue. @Tnu02
