### ISSUE TITLE
Bearer Token Should be able to get passed for Session Continuity

### ISSUE THREAD

**Issue by SRvSaha** [SRvSaha/CoWinVaccineSlotFinder#41]
**Is your feature request related to a problem? Please describe.**
Bearer Tokens are used as Auth Tokens using OpenID Connect. So, usually what happens is, if a user has started the App and feel that something is wrong in the config file, he has to close the App. After fixing the config, if he tries again, he needs to provide the captcha once again.

This is a bit difficult to get OTP every time on time.

**Describe the solution you'd like**
Provide a way to user to enter their Auth Token and also show them their current Auth Token, so that they can leverage it

**Describe alternatives you've considered**
N/A

**Additional context**
Developers will have easy time in debugging when Bearer Tokens can be passed

**Comment by SRvSaha** [comment]
Changes integrated with commit 849acdaf2f5de4d9ab6a69997bfb17c6f877a45f

**Comment by deepak-batra** [comment]
Does the bearer token method remove the need for OTP every 15 mins?

**Comment by SRvSaha** [comment]
@deepak-batra No, it just helps you in a way that suppose you already have a valid token from browser, you can use it in App. Also, let's say you have used the app, but had to close it, you can continue with the previous session, without requesting new OTP.
