### ISSUE TITLE
Unable to book

### ISSUE THREAD

**Issue by Tnu02** [SRvSaha/CoWinVaccineSlotFinder#42]
Faced 2 issues today.

1. Slot showing late on the 4.0 version
2. Getting unathenticated access error

![unathenciated](https://user-images.githubusercontent.com/83922100/118758672-18266100-b88d-11eb-9f71-512c696bc8b1.jpg)

**Comment by SRvSaha** [comment]
Hi @Tnu02,
1. No changes in slot showing logic apart from the logic changes to dose based capacity, so that should not have happened.
2. Unauthorized because your session has timed out when trying to get captcha

**Comment by Tnu02** [comment]
Aaah.. It should resend the OTP den 😀

For today's booking it was just 1st Dose and same mentioned in the file.. But the site it started showing slots before alerted by the app.. Not sure why but that happened.

**Comment by SRvSaha** [comment]
@Tnu02 Yes, the Resend OTP has been Care in v4.1.0. Check it out.

**Comment by Tnu02** [comment]
> @Tnu02 Yes, the Resend OTP has been Care in v4.1.0. Check it out.

Yup, its working now.. Thanks.
