### ISSUE TITLE
[Question]Does auto-captcha work? 

### ISSUE THREAD

**Issue by deepak-batra** [SRvSaha/CoWinVaccineSlotFinder#43]
I've integrated something very similar in a python script but I'm not sure how to write tests to verify if it works. The captcha integrated here works similarly. I was wondering if you've tested that either via a UT or on cowin.

**Comment by SRvSaha** [comment]
@deepak-batra, I have tested it, it works. Integration is done but will be released with v4.1.0. 
To Write Tests, get an SVG and then manually check it's value and asset if it is equal to the computed one

**Comment by Madhumantisg** [comment]
I'm trying to write code it Python too. OTP generation was working until 17th but from yesterday I keep getting  403 request blocked when I try to generate OTP. Any suggestions please?
Below is the error message:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: t5plHD5wFv3ZCxqsYsyXAkn4Q3DOUXYD3Kqa_cETsr_RhqhgBN775w==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>



Please help! thanks

**Comment by deepak-batra** [comment]
> I'm trying to write code it Python too. OTP generation was working until 17th but from yesterday I keep getting 403 request blocked when I try to generate OTP. Any suggestions please?
> Below is the error message:
> 
> <TITLE>ERROR: The request could not be satisfied</TITLE>
> # 403 ERROR
> ## The request could not be satisfied.
> Request blocked. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
> If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation. 
> Generated by cloudfront (CloudFront)
> Request ID: t5plHD5wFv3ZCxqsYsyXAkn4Q3DOUXYD3Kqa_cETsr_RhqhgBN775w==
> Please help! thanks

You might need a user-agent. If you're already providing that then it might be an IP issue. I was running the script from a VM outside India and I was getting the same error.

**Comment by deepak-batra** [comment]
> @deepak-batra, I have tested it, it works. Integration is done but will be released with v4.1.0.
> To Write Tests, get an SVG and then manually check it's value and asset if it is equal to the computed one

Cool. 👍 Closing this.

**Comment by SRvSaha** [comment]
@deepak-batra  If you feel, I could help you, feel free to Star the repo and share it with your buddies! Also share your feedback by comment/share/like in the associated [LinkedIn Post](https://www.linkedin.com/feed/update/urn:li:activity:6796093424492720128/) That'll be used as References/Testimonials in the Application and will increase the credibility of the App.

**Comment by jayeshp004** [comment]
Its still asking for captcha. I think sometimes the feature doesn't work.

**Comment by SRvSaha** [comment]
> 
> 
> Its still asking for captcha. I think sometimes the feature doesn't work. (version 4.1.0)

@jayeshp004 Check your config file's `"AutoReadCaptcha": "<REPLACE_ME>", // Use either true or false in the <REPLACE_ME> section; By default false;
// True means No need to enter captcha, Captcha will be automatically computed by AI Model, False means captcha needs to be entered manually in the Captcha Popup window
`
