### ISSUE TITLE
Program Stuck in Fetching Resources

### ISSUE THREAD

**Issue by malayilneil** [SRvSaha/CoWinVaccineSlotFinder#44]
Hi, The Program is stuck in fetching resources once I have submitted the top. I have modified the json file as per your instructions and also modified the file to use district instead of Pincode. 

Let me know how to solve this. Thanks in advance.

**Comment by SRvSaha** [comment]
Hi @malayilneil , can you please share some screenshot? Also, a new version will be published tonight, can you please try with that ?

**Comment by malayilneil** [comment]
Cool I'll wait till its done!

**Comment by SRvSaha** [comment]
Hi @malayilneil, Release [v4.1.0 ](https://github.com/srvsaha/CoWINVaccineSlotFinder/releases/latest) is now  live, with the milestone of AutoCaptcha Feature!
Check it out and Star the Repo so that it appears higher in Github Search and help others as well

**Comment by SRvSaha** [comment]
> 
> 
> Hi, The Program is stuck in fetching resources once I have submitted the top. I have modified the json file as per your instructions and also modified the file to use district instead of Pincode.
> 
> Let me know how to solve this. Thanks in advance.

@malayilneil Verbose mode has also been added in Release [v4.1.0 ](https://github.com/srvsaha/CoWINVaccineSlotFinder/releases/latest) which will show what is being searched and slots found or not, so that you'll know for sure whether the Application is really stuck or not.

**Comment by malayilneil** [comment]
@SRvSaha How do you activate verbose mode?

**Comment by SRvSaha** [comment]
> 
> 
> @SRvSaha How do you activate verbose mode?

@malayilneil By default, it runs in verbose mode, where you'll be informed that tried searching from XYZ centres, slots not found or slots found!
