### ISSUE TITLE
Version 4.1.0

### ISSUE THREAD

**Issue by Tnu02** [SRvSaha/CoWinVaccineSlotFinder#45]
Hey @SRvSaha Just curious, when will we get 4.1.0.  :)

**Comment by SRvSaha** [comment]
Tonight
Regards

*Saurav Saha*
Software Development Engineer
Bharat Petroleum Corporation Limited
Mumbai, India
Ph: *+91 9402508957(M) *
LinkedIn:
*Saurav Saha*
<http://www.linkedin.com/in/srvsaha>

**Comment by SRvSaha** [comment]
Hi @Tnu02, Release [v4.1.0 ](https://github.com/srvsaha/CoWINVaccineSlotFinder/releases/latest) is now  live, with the milestone of AutoCaptcha Feature!
Check it out and share your feedback.
