### ISSUE TITLE
Auto Catpcha working?

### ISSUE THREAD

**Issue by akshay8043** [SRvSaha/CoWinVaccineSlotFinder#47]
auto captcha didn't work for me on 4.1.0

received popup for captcha had to manually put but it was already booked

**Comment by akshay8043** [comment]
![image](https://user-images.githubusercontent.com/32493756/118959285-cd394600-b97f-11eb-8909-f791f90ec7bb.png)

I thought it would auto-input captcha

**Comment by SRvSaha** [comment]
Hi @akshay8043, I think you haven't changed in the config.
Check this part from MUST Change section in CONFIG: https://github.com/SRvSaha/CoWinVaccineSlotFinder#configuration-changes
> "AutoReadCaptcha": "<REPLACE_ME>", // Use either true or false in the <REPLACE_ME> section; By default false;
// True means No need to enter captcha, Captcha will be automatically computed by AI Model, False means captcha needs to be entered manually in the Captcha Popup window

**Comment by SRvSaha** [comment]
@akshay8043 If you are trying again, just change 
`"AutoReadCaptcha": true`. By default Manual is chosen since not all users would want Auto Captcha to work on their behalf!

**Comment by akshay8043** [comment]
Thanks, Sorry I missed that

**Comment by akshay8043** [comment]
I configured this and hope auto captcha works if slots are available.

**Comment by SRvSaha** [comment]
@akshay8043 It will work, I have done for 2 folks today

**Comment by debanshur** [comment]
@SRvSaha The captcha worked once for me but didnt work the second time. Is there any logs I could send? What could be the issue?

**Comment by SRvSaha** [comment]
Hi @debanshu, Sorry that happened with you. Logs aren't available right now, shall be done in upcoming version. Can you please try one more time and see if it work? If the issue still persists, let me know
