### ISSUE TITLE
Script continuous to run after wrong OTP inserted.

### ISSUE THREAD

**Issue by akshay8043** [SRvSaha/CoWinVaccineSlotFinder#49]
Script continuous to run after the wrong OTP inserted.

so will it book the slot?

![image](https://user-images.githubusercontent.com/32493756/118969679-f6ab9f00-b98a-11eb-8647-2c824fae361a.png)

**Comment by SRvSaha** [comment]
@akshay8043 This is strange, but happens sometimes, in case the backend system of CoWIN is not validating the request for fetching data properly.
But did you try and replicate the same scenario over and over again? I faced similar thing but then it asks for session validation

**Comment by akshay8043** [comment]
Is it because of the session is still valid?

For instance,

My session would be still active causing this to continue running the script?

or maybe you have explicitly added 15 minute timer in the application causing me to regenerate OTP.

**Comment by SRvSaha** [comment]
@akshay8043 There is no explicit checks of time. If OTP is invalid, Fetch Resources should have given 401 and new OTP would have generated. Since this is not working always, I will add explicit conditions for handling this.

**Comment by SRvSaha** [comment]
@akshay8043  Can you please test the scenario as per the description in #79 for machine and see if it works. Need some feedback that it works, before making a new release. See the discussions for all different types of test scenarios. Would be happy if you can contribute.
