### ISSUE TITLE
Age criteria Error

### ISSUE THREAD

**Issue by 5HU8H** [SRvSaha/CoWinVaccineSlotFinder#50]
I've been getting this error lately. Any fix?
<img width="832" alt="Screenshot 2021-05-20 at 5 02 38 PM" src="https://user-images.githubusercontent.com/68404136/118972229-f1038880-b98d-11eb-8220-4041fbd0fe28.png">

**Comment by SRvSaha** [comment]
@5HU8H Can you please share your config file by removing Mobile Number and Beneficiary IDs? Also, are you running it on mac or just Window CMD with MAC OS's Terminal theme.

**Comment by 5HU8H** [comment]
I'm running this on a mac using Crossover.
<img width="832" alt="Screenshot 2021-05-20 at 5 16 38 PM" src="https://user-images.githubusercontent.com/68404136/118973618-7c314e00-b98f-11eb-8400-592b8e871709.png">

**Comment by 5HU8H** [comment]
@SRvSaha I'm getting the same error on a windows machine.
![image](https://user-images.githubusercontent.com/68404136/118976332-87d24400-b992-11eb-8061-175a6f6f92f5.png)

**Comment by 5HU8H** [comment]
Thanks! it worked!

**Comment by SRvSaha** [comment]
@5HU8H Awesome! Can you please let me know about the notifier thing? The OTP Beeps, do it work with Crossover Application. Also, you may share your feedback here: : [Post](https://www.linkedin.com/feed/update/urn:li:activity:6796093424492720128/)

**Comment by 5HU8H** [comment]
None of the sounds work. The rest of it works flawlessly!

**Comment by SRvSaha** [comment]
@5HU8H Yeah, thought so, cause the sounds use Windows Specific APIs. Anways, thanks!

**Comment by SRvSaha** [comment]
@5HU8H @Roozb Can you please test the scenario as per the description in #79 for machine and see if it works. Need some feedback that it works, before making a new release. See the discussions for all different types of test scenarios. Would be happy if you can contribute.
