### ISSUE TITLE
Proper message doesn't show up when Vacccination Centre is Not Available

### ISSUE THREAD

**Issue by SRvSaha** [SRvSaha/CoWinVaccineSlotFinder#51]
**Describe the bug**
There are scenarios where Vaccination Centres are Blank.
In that Case, users are not shown any message.

**To Reproduce**
1. Open the App
2. Select Any PIN Code from which there are no CVCs.
3. You'll see no messages being shown to user as no available slots.

**Expected behavior**
Should tell the user that no centres available.

**Screenshots**
![image](https://user-images.githubusercontent.com/13312352/118973039-e1387400-b98e-11eb-89c2-285d9002765e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
NA

**Comment by saurabhkrr** [comment]
i tried running this and whenever a slot is available it doesn't show up. it says no slots available but notifications for available slot came from various alerts.

**Comment by SRvSaha** [comment]
@saurabhkrr, Usually the alerts are not shown in realtime, so they might have some stale data. If you still feel the same is happening, please check the CoWIN Portal after logging in at that time and then check if slots are really avaiable. If yes, then we'll look into it.

**Comment by saurabhkrr** [comment]
yes i checked the cowin portal, slots came up at that time.

**Comment by saurabhkrr** [comment]
hey. thanks i was able to secure a slot.. but i have a query can we book 3 slots together ?

**Comment by SRvSaha** [comment]
@saurabhkrr , yes you can if you're having the same beneficiary ID for all 3. Else, you would have to run the program 3 times.

**Comment by SRvSaha** [comment]
> 
> 
> hey. thanks i was able to secure a slot.. but i have a query can we book 3 slots together ?

Hi @saurabhkrr, glad to know that you could book the slot! Please feel free to show support from Starring the Repo and sharing it with your friends. You may also like to share your testimonial here: https://www.linkedin.com/feed/update/urn:li:activity:6796093424492720128/

**Comment by saurabhkrr** [comment]
but reference id is different for 3 different person on that phone number

**Comment by SRvSaha** [comment]
> 
> 
> but reference id is different for 3 different person on that phone number

Yes, basically you can put multiple beneficiary ids and try booking, provided all are registered under the same phone number.
This is how you do it for multiple beneficiaries:
```
"BeneficiaryIds": [ "REPLACE_WITH_YOUR_BENEFICIARY_ID_1", "REPLACE_WITH_YOUR_BENEFICIARY_ID_2" ] 
// You'll get the beneficiary ID from Step 4 above. 
// If you have only 1 beneficiary ID then Use it in the <REPLACE_WITH_YOUR_BENEFICIARY_ID_1> section and remove rest like "REPLACE_WITH_YOUR_BENEFICIARY_ID_2" eg. ["1111111111111111"]. 
// If you have multiple beneficiaries for which you want to do booking, added them comma separated eg. ["11111111111111", "22222222222222", "33333333333333"]
```

If not, they you have to do them separately.

**Comment by saurabhkrr** [comment]
![IMG20210522125413](https://user-images.githubusercontent.com/76863660/119218217-e9aebd00-bafc-11eb-9056-4f213577681e.jpg)

**Comment by SRvSaha** [comment]
@saurabhkrr This is happening as probably you are crossing the Rate Limiting Limit they have set for the API.

Change the config's 
`SleepIntervalInMilliseconds` to 5000 and try again

**Comment by SRvSaha** [comment]
@saurabhkrr Check #53
