### ISSUE TITLE
Random user agent for each API call

### ISSUE THREAD

**Issue by predictablyrandom** [SRvSaha/CoWinVaccineSlotFinder#54]
**Is your feature request related to a problem? Please describe.**
Currently the API calls returns 403 a lot of times.

**Describe the solution you'd like**
Perhaps using a random user agent like in this python package https://pypi.org/project/fake-useragent/ should fix it?.

**Comment by SRvSaha** [comment]
@predictablyrandom Yeah, need to do that equivalent in .NET

**Comment by predictablyrandom** [comment]
Perhaps you can just have a list of the agents & choose one of the elements from the list at random?

**Comment by SRvSaha** [comment]
@predictablyrandom Yes, can be done. Can you please provide list of Accepted UAs?

**Comment by predictablyrandom** [comment]
https://github.com/rummolprod999/RandomUserAgent/blob/master/RandomUserAgent/RandomUA.cs this file has the list & the relevant code snippet @SRvSaha. More the merrier I think, possibility of same agent being used for subsequent calls become very less.

**Comment by SRvSaha** [comment]
> 
> 
> https://github.com/rummolprod999/RandomUserAgent/blob/master/RandomUserAgent/RandomUA.cs this file has the list & the relevant code snippet @SRvSaha. More the merrier I think, possibility of same agent being used for subsequent calls become very less.

@predictablyrandom Understand that more will be better. Just was thinking for restricting to some small set, as we don't know which all are supported by CoWIN. Can you help in writing automatic testing of one endpoint using all possible UAs and see if all are supported by CoWIN?

**Comment by predictablyrandom** [comment]
@SRvSaha I have tried the python package which I had shared before that works without any issue. Let me check

**Comment by SRvSaha** [comment]
> 
> 
> @SRvSaha I have tried the python package which I had shared before that works without any issue. Let me check

Yeah, please just check the whether the UAs are same in both

**Comment by predictablyrandom** [comment]
checked entries for Firefox, Chrome, Opera & Safari from https://github.com/rummolprod999/RandomUserAgent/blob/master/RandomUserAgent/RandomUA.cs they seem to work fine

**Comment by SRvSaha** [comment]
Awesome! Shall add them then! @predictablyrandom

**Comment by predictablyrandom** [comment]
@SRvSaha In case its not already done, perhaps pass `Cache-Control: no-cache, no-store, max-age=0, must-revalidate` in headers too?

**Comment by SRvSaha** [comment]
@predictablyrandom That’s a good suggestion, shall do that

**Comment by SRvSaha** [comment]
@predictablyrandom Observed today that after some time, IP was getting throttled. Any ideas if they have added IP Throttling? Any workaround?

**Comment by Rajat-dey** [comment]
![Screenshot (107)](https://user-images.githubusercontent.com/37307994/119225504-c0545800-bb21-11eb-8330-d97d8c1d27aa.png)
Is that about IP got blocked?? @SRvSaha

**Comment by SRvSaha** [comment]
@Rajat-dey Yeah, seem like they had added some throttling.

Check this #53

**Comment by Tnu02** [comment]
Have you found any solution @SRvSaha for this IP throttling  ??

**Comment by SRvSaha** [comment]
@Tnu02 The Rate Limit as I feel by observation is 100 Hits from IP within 5 minutes. 
So, if you are searching for 1 PIN Code then you'll have to keep the SleepInterval as 3000, similarly if you have 2 PIN Codes, it will be 6000 and so on and so forth so that IP is within the rate limit. Another way out is to use two different network IPs and then keep switching between the once you see the error. You can copy the Bearer Token you get after entering OTP, and then on subsequent run from different IP. you have use that in the config file so that re-OTP is not required. This the only work around as of now. Also, try varying the User Agent, might help.

**Comment by Tnu02** [comment]
> @Tnu02 The Rate Limit as I feel by observation is 100 Hits from IP within 5 minutes. 
> So, if you are searching for 1 PIN Code then you'll have to keep the SleepInterval as 3000, similarly if you have 2 PIN Codes, it will be 6000 and so on and so forth so that IP is within the rate limit. Another way out is to use two different network IPs and then keep switching between the once you see the error. You can copy the Bearer Token you get after entering OTP, and then on subsequent run from different IP. you have use that in the config file so that re-OTP is not required. This the only work around as of now. Also, try varying the User Agent, might help.

I am using 10000 for 2 pin code still after few time start getting the game error.. 😀

**Comment by xxxAng** [comment]
@SRvSaha what about if we search 1 district instead of pincodes ?
Tried with 1 district 7 seconds, still getting rate limited :(

**Comment by SRvSaha** [comment]
@Tnu02 If possible, use Hotspot from different different ISPs for every 100 Hits/5 minutes.

**Comment by SRvSaha** [comment]
> 
> 
> @SRvSaha what about if we search 1 district instead of pincodes ?
> Tried with 1 district 7 seconds, still getting rate limited :(

Yes this is a bit strange, CoWIN is not handling IP Throttling properly, similar issue is being faced by others as well: Check here: https://github.com/bombardier-gif/covid-vaccine-booking/issues/270

**Comment by predictablyrandom** [comment]
> @predictablyrandom Observed today that after some time, IP was getting throttled. Any ideas if they have added IP Throttling? Any workaround?

@SRvSaha yes seems like they have done some sort of IP throttling, the only way I am aware of is to route requests randomly through different proxies (https://www.scrapehero.com/how-to-rotate-proxies-and-ip-addresses-using-python-3/), this could also be tricky because requests could be blocked if they are coming from outside of India.

**Comment by SRvSaha** [comment]
Hi @predictablyrandom, your suggestions are integrated in [v4.2.0](https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/latest) is up now. Check it out and share your feedback. This release tries to address some of the issue of IP Throttling.

**Comment by SRvSaha** [comment]
@Rajat-dey Now the Throttling Interval and Throttling Time is there as a part of Config File to modify along with the changes in Sleep Interval. Give it a try in [v4.2.0](https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/latest) is up now. Check it out and share your feedback. This release tries to address some of the issue of IP Throttling.
See if it helps

**Comment by SRvSaha** [comment]
> 
> 
> Have you found any solution @SRvSaha for this IP throttling ??

[v4.2.0](https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/latest) is up now. Check it out and share your feedback. This release tries to address some of the issue of IP Throttling.
