### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Tnu02** [SRvSaha/CoWinVaccineSlotFinder#58]
Hey @SRvSaha , Would it be possible to pause the request in the middle off session using any keyboard shortcut or something so that when ever we want, we resume the checking again.

Just thought of it.. What do you think..

**Comment by veeru1saini1** [comment]
maybe just do a hotkey thing where one could just pause it by using hotkey and resume back the search

**Comment by SRvSaha** [comment]
Reason #68
