### ISSUE TITLE
Error shown

### ISSUE THREAD

**Issue by Roozb** [SRvSaha/CoWinVaccineSlotFinder#62]
Please let me know what's the error ...

![appsettings - Notepad 24-05-2021 12_44_12](https://user-images.githubusercontent.com/84204114/119310983-2362fd80-bc8e-11eb-83f6-86e3d15e7921.png)
![C__Users_Roozbeh_Desktop_CoWinReleasesv4 2 0_CoWin Core exe 24-05-2021 12_41_15](https://user-images.githubusercontent.com/84204114/119310992-265dee00-bc8e-11eb-9728-e1b2ac4a3490.png)

**Comment by SRvSaha** [comment]
@Roozb The Structure of Districts has changed, now you don't need to provide the name of the District, only the District Codes.
Try to Replace with `Districts: ["395", "392"]`

Further, you can check the issue using any Online JSON Parser, it will pin point your where the issue lies.
Let me know if it helps!

**Comment by Roozb** [comment]
Is this correct now ?

![C__Users_Roozbeh_Desktop_CoWinReleasesv4 2 0_CoWin Core exe 24-05-2021 13_10_46_LI](https://user-images.githubusercontent.com/84204114/119314332-4394bb80-bc92-11eb-8a15-d59a98136ac3.jpg)

**Comment by SRvSaha** [comment]
Yes @Roozb it is correct. However, seems like you are getting no centres as there are no centres being returned from CoWIN API.
See if you get can see in CoWIN Portal.

**Comment by SRvSaha** [comment]
@Roozb Can you please test the scenario as per the description in #79 for machine and see if it works. Need some feedback that it works, before making a new release. See the discussions for all different types of test scenarios. Would be happy if you can contribute.
