### ISSUE TITLE
How to run this in Linux/Mac?

### ISSUE THREAD

**Issue by aman-3003** [SRvSaha/CoWinVaccineSlotFinder#63]
Is there any possible way to run this on any other operating system other than windows?

**Comment by SRvSaha** [comment]
@aman-3003 Hi, as of now it for Windows only, WIP in branch `ui-dependency-remove` where WIP to make it cross platform. It is almost done and shall be released as a part of v5.0.0

However, if you want to run it as of now, use CrossOver or some other software where you can run EXE in Mac/Linux.  Only the Notification Beeps won't work. 

Related: #50

**Comment by aman-3003** [comment]
Worked perfectly with CrossOver. Thanks 👍🏻

**Comment by SRvSaha** [comment]
@aman-3003 Awesome! Feel free to share you feedback here: https://shawt.io/r/sYx

Closing the Issue, Pinning it in case it helps someone else.

**Comment by SRvSaha** [comment]
Cross Platform Support is enabled with Version 5.0.0 Release.

Linux: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.0.0-linux
Mac: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.0.0-osx
Windows: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.0.0-windows

**Comment by SRvSaha** [comment]
Further Troubleshooting and Guide: #74

**Comment by SRvSaha** [comment]
Follow the ReadMe for detailed steps here: https://github.com/SRvSaha/CoWinVaccineSlotFinder#how-to-run-on-macoslinux-systems-
