### ISSUE TITLE
Where is the problem?

### ISSUE THREAD

**Issue by ansi82** [SRvSaha/CoWinVaccineSlotFinder#64]
[https://ibb.co/fNWLNpv
https://ibb.co/YfyyYJk](url)

**Comment by SRvSaha** [comment]
Links aren’t valid. Share here directly @ansi82

**Comment by ansi82** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/84778690/119501093-293c0a00-bd86-11eb-8c99-c873c14e3082.png)
![Screenshot (33)](https://user-images.githubusercontent.com/84778690/119501145-378a2600-bd86-11eb-9684-d428d448c104.png)

**Comment by SRvSaha** [comment]
@ansi82 You have removed PINCodes from thw config file. Don’t remove anything. If you feel you don’t want to search by PIN, just set the IsSearchToBeDoneByPINCode as false and leave it as it is. Also, I see there are some more missing stuffs in config file, make sure you don’t remove anything. Just fill what’s required. Check Readme MUST CHANGE Section for more details

**Comment by ansi82** [comment]
thanks, solved

**Comment by SRvSaha** [comment]
Enjoy and feel free to Star the Repo, if I could help you in any way! Share it in your circles @ansi82
