### ISSUE TITLE
Mobile feature request

### ISSUE THREAD

**Issue by hpk22** [SRvSaha/CoWinVaccineSlotFinder#66]
Hello..Loved your project..
I just had a feature request that can you add option to use this on mobile devices also.it would be very efficient for all people especially less tech oriented.
Would be very pleased if you can do it.
Thanks 😊

**Comment by SRvSaha** [comment]
Hi @hpk22 we are trying but there are certain limitations hence till now mobile application is not available.
Check see if it is feasible. Star the Repo if the Application was of use for you.

**Comment by hpk22** [comment]
Not necessarily an application but extension or running script on cowin
platform would be great. And yes already starred 👍

**Comment by SRvSaha** [comment]
Reason #68
