### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by hpk22** [SRvSaha/CoWinVaccineSlotFinder#67]
Hey..can you please add option for time slot preference. like you could  ask 1,2,3,4 from users to get there desired time slot

**Comment by SRvSaha** [comment]
@hpk22 Yes that is possible, however there is a caveat. Not all Centres have 4 slots, some might have 1 or some might have 4. Hence it will be tough to get it from User Input. 
Would you like to explain the workflow considering the above limitation?

**Comment by SRvSaha** [comment]
Reason: #68
