### ISSUE TITLE
[ANNOUNCEMENT] PROJECT PUT ON INDEFINITE HOLD

### ISSUE THREAD

**Issue by SRvSaha** [SRvSaha/CoWinVaccineSlotFinder#68]
## **THAT BEING SAID, THE APPLICATION WILL BE AVAILABLE FOR USE, BUT NO MAINTENANCE WILL BE DONE OF THE APPLICATION** 

Reference: https://github.com/cowinapi/developer.cowin/issues/333

**Comment by SRvSaha** [comment]
There will be a final release v5.0.0 with support for Mac, Linux and Windows and that's it. Thanks everyone for your time, support and all love. #covid19help

**Comment by Tnu02** [comment]
Hey @SRvSaha.. Is it safe to use v5 or any older version.!! Or we just stop using it.. Please help..

**Comment by SRvSaha** [comment]
> 
> 
> Hey @SRvSaha.. Is it safe to use v5 or any older version.!! Or we should just stop using it.. Please help..

You may use it. But there will be no more developments and support. Check out the full T&C in the description to know in details. I can't comment on it. It's controvertial.

**Comment by SRvSaha** [comment]
Cross Platform Support is enabled with Version 5.0.0 Release.

Linux: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.0.0-linux
Mac: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.0.0-osx
Windows: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.0.0-windows

**Comment by SRvSaha** [comment]
#88
