### ISSUE TITLE
OTP Error

### ISSUE THREAD

**Issue by yashk2103** [SRvSaha/CoWinVaccineSlotFinder#7]
While running the executable file, I'm getting an OTP error message and the script exits on it's own

**Comment by SRvSaha** [comment]
Did you read the README file and replaced the values which needed to be replaced? Seems like you haven’t replaced with correct mobile number in Config File

**Comment by yashk2103** [comment]
Sorry for bothering you, I figured it out. I had put tha values in between the <___> brackets. Thats why the script couldnt read it. Now it works perfect.

Also, massive thanks for this and your contribution :)

**Comment by SRvSaha** [comment]
Glad it helped. Feel free to star the repo and share!
