### ISSUE TITLE
Not able to book 45+ slot

### ISSUE THREAD

**Issue by 520rahul** [SRvSaha/CoWinVaccineSlotFinder#71]
**Describe the bug**
For booking 45+ i changed minimum age to 45 and max to 99 but when slot came it showed nothing for 45+ slots.  I again changed max age to blank but still same issue.  What should b the correct method for 45+

**Comment by 520rahul** [comment]
@SRvSaha plz help

**Comment by SRvSaha** [comment]
@520rahul The Min Age will be 45 only, that’s correct. Slots were not shown probably because the scenario might be that Slots came when the profram went for sleep and then when it work up after sometime, slots were gone.

You may check other settings and sleepintervalis milliseconds.

**Comment by 520rahul** [comment]
> @520rahul The Min Age will be 45 only, that’s correct. Slots were not shown probably because the scenario might be that Slots came when the profram went for sleep and then when it work up after sometime, slots were gone.
> 
> You may check other settings and sleepintervalis milliseconds.

Sir, there were 3 centres 1 after another. And my sleep intervel is set to 10, but it did not even tried to book slot.  Can u plz share what should b settings for 45+.  As when i left maximum age blank, system showed me error

**Comment by SRvSaha** [comment]
@520rahul Sleep Interval of 10 milliseconds is very less. Keep atleast 1000 milliseconds.

Keep tgese settings
MinAge: 45
MaxAge: 100

**Comment by 520rahul** [comment]
> @520rahul Sleep Interval of 10 milliseconds is very less. Keep atleast 1000 milliseconds.
> 
> Keep these settings
> MinAge: 45
> MaxAge: 100

Sorry sir by mistake i wrote 10 instead of 1000. And i use different ips, still when slot came for 45+ it did nothing and showed the slots as not viabale. Plz check its a request for 45+

**Comment by SRvSaha** [comment]
@520rahul Unless you have made any changes is other stuffs, it should work. Share you config file after removing confidential information

**Comment by 520rahul** [comment]
> @520rahul Unless you have made any changes is other stuffs, it should work. Share you config file after removing confidential information

i am using v 4.1 and did booking yesterday for 18-44 but was not able to book for 45+. below is my file:-

{
  "CoWinAPI": {
    "PublicAPI": {
      "FetchCalenderByDistrictUrl": "https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict",
      "FetchCalenderByPINUrl": "https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin"
    },
    "ProtectedAPI": {
      "IsToBeUsed": true,
      "FetchCalenderByDistrictUrl": "https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByDistrict",
      "FetchCalenderByPINUrl": "https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByPin",
      "ScheduleAppointmentUrl": "https://cdn-api.co-vin.in/api/v2/appointment/schedule",
      "CaptchaGenerationUrl": "https://cdn-api.co-vin.in/api/v2/auth/getRecaptcha",
      "BeneficiaryIds": [ "12345678912345" ]
    },
    "Auth": {
      "IsToBeUsed": true,
      "OTPGeneratorUrl": "https://cdn-api.co-vin.in/api/v2/auth/generateMobileOTP",
      "OTPValidatorUrl": "https://cdn-api.co-vin.in/api/v2/auth/validateMobileOtp",
      "Secret": "U2FsdGVkX18vDwDor+oOIG7vSUnINtlc/pxQcNiBulCm8LT5Sza+aIISKLqImbpMnRYgsN2QACPhggLWgZEpQg==",
      "AutoReadCaptcha": true, // Use either true or false; By default false; True means No need to enter captcha, False means captcha needs to be entered manually
      "BearerToken": "", // If you already have bearer token, which you'll get after entering OTP, you can put it here for subsequent usage. But default, it will be blank which means new sessions will be generated and OTP would be needed
      "Mobile": "9999999999"
    },
    "SleepIntervalInMilliseconds": 1000,
    "TotalIterations": 10000,
    "SpoofedUserAgentToBypassWAF": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "SelfRegistrationPortal": "https://selfregistration.cowin.gov.in",
    "MinAgeLimit": 45,
    "MaxAgeLimit": 99,
    "MinimumVaccineAvailability": 1,
    "VaccineType": "COVAXIN", // Blank Implies Any VaccineType: COVISHIELD OR COVAXIN OR SPUTNIK V; Default is any type of Vaccine
    "DoseType": 2,
    "VaccineFeeType": "Free", // Blank Implies Any VaccineFeeType: Free or Paid; Default is Free
    "VaccinationCentreName": "", // Blank implies All Vaccination Centres in the District/PINCodes, which is default
    "IsSearchToBeDoneByPINCode": true, // Set this as True if you want to set by PINCode
    "PINCodes": [
      "111111"
      
    ],
    "IsSearchToBeDoneByDistrict": false, // Set this is True if you want to search By District
    "Districts": [
      "REPLACE_ME_WITH_YOUR_DISTRICT_CODE_1",
      "REPLACE_ME_WITH_YOUR_DISTRICT_CODE_2"
    ],
    "DateToSearch": "" // DD-MM-YYYY Format, Blank implies tomorrow's day; Date Searched is upto 7 days from the date in DateToSearch
  },
  "Proxy": {
    "IsToBeUsed": "false",
    "Address": ""
  },
  "App": {
    "LatestVersion": {
      "FetchDetailsAPIEndpoint": "https://api.github.com/repos/srvsaha/CoWINVaccineSlotFinder/releases/latest"
    }
  }
}

**Comment by SRvSaha** [comment]
@520rahul Share the PIN Code for which you are searching so that I can replicate the scenario. Config seems okay. Just one thing that I want to point out is that are you sure that slots are available for Dose Type 2 of type COVAXIN and Free for your PIN Code?
If any of this doesn't match, you won't get the available slots.

**Comment by 520rahul** [comment]
Ye

> @520rahul Share the PIN Code for which you are searching so that I can replicate the scenario. Config seems okay. Just one thing that I want to point out is that are you sure that slots are available for Dose Type 2 of type COVAXIN and Free for your PIN Code?
> If any of this doesn't match, you won't get the available slots.

Yes sir slot were coming and going in front of me for 45+. And i doubled checked that covaxin was available in all 3 centres for dose 1 and dose 2 both. Pin code is 301001

**Comment by 520rahul** [comment]
@SRvSaha one more request sir. In version 5.0 plz do throttling settings as like v 4.1, bcoz in 4.2 fatel error comes very frequently even if ip is changed

**Comment by SRvSaha** [comment]
@520rahul I will try to do whatever is possible. Rather than just asking for suggestions, do you mind Starring the repo as well and sharing with other so that it helps them as well.?

**Comment by 520rahul** [comment]
> @520rahul I will try to do whatever is possible. Rather than just asking for suggestions, do you mind Starring the repo as well and sharing with other so that it helps them as well.?

I just did starring the repo. Thank u so much for listening to us patiently and resolving our problems. And sharing this with others also so that max people get benefit of it

**Comment by 520rahul** [comment]
@SRvSaha sir did u figure out someting

**Comment by SRvSaha** [comment]
Yes, Issue resolved with v5.0.0. Give it a try:

Cross Platform Support is enabled with Version 5.0.0 Release.

Linux: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.0.0-linux
Mac: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.0.0-osx
Windows: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.0.0-windows

**Comment by 520rahul** [comment]
> Yes, Issue resolved with v5.0.0. Give it a try:
> 
> Cross Platform Support is enabled with Version 5.0.0 Release.
> 
> Linux: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.0.0-linux
> Mac: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.0.0-osx
> Windows: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.0.0-windows

Ok sir thanks.  I shall try it today😊

**Comment by SRvSaha** [comment]
@520rahul v5.1.0 is now up and running! Check it out and share your feedback. Share in your circles:
Windows: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.1.0-windows
MacOSX: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.1.0-osx
Linux: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.1.0-linux

**Comment by 520rahul** [comment]
Thank u s much @SRvSaha i will definitely share my feedback

**Comment by SRvSaha** [comment]
> 
> 
> Thank u s much @SRvSaha i will definitely share my feedback

Could you book? Close the thread if the issue is resolved.

**Comment by 520rahul** [comment]
> > Thank u s much @SRvSaha i will definitely share my feedback
> 
> Could you book? Close the thread if the issue is resolved.

Thank u so much sir.  I could book the slot due to ur help.  God bless u.

**Comment by SRvSaha** [comment]
Awesome @520rahul! Great to hear that. Happy to help! Please help others to book as well and share it with the needy.

URL: https://shawt.io/r/sYv

Also, you can share you testimonial here in the comment section so that it reaches out to more people and it increases the credebility of the App.

URL: https://shawt.io/r/sYx
