### ISSUE TITLE
MacOs File Path Problem for appsettings.json

### ISSUE THREAD

**Issue by aman-3003** [SRvSaha/CoWinVaccineSlotFinder#74]
![Screenshot 2021-05-31 at 11 21 57 AM](https://user-images.githubusercontent.com/59678544/120146456-bd80f380-c202-11eb-8f01-95d5c46fed52.png)

It takes the appsettings.json file from the path /Users/[user-name]/appsettings.json instead from the folder itself. It works when the file is moved to this /Users/[user-name]/appsettings.json

**Comment by SRvSaha** [comment]
@aman-3003 Actually, I didn't get time to update the readme.
So basically if you open Terminal in the folder where you have extracted the OSX Release, there will be a run.sh file.

So, just do this is your Terminal: `bash run.sh` and it should work fine.

Probably because you are double clicking the CoWinVaccineSlotFinder executatable, so by default it searches within default path.
Try it and let me know.

**Comment by aman-3003** [comment]
Yesss now it works perfectly 👍🏻

**Comment by SRvSaha** [comment]
@aman-3003 Can you please test the scenario as per the description in #79 for Mac and see if it works. Need some feedback that it works, before making a new release. See the discussions for all different types of test scenarios. Would be happy if you can contribute.

**Comment by aman-3003** [comment]
When in appsettings.json "ProtectedAPI" is "true" it works till 20 tries then it throttles. The fix you provided to use the PublicAPI for searching works but when it is changed back to using the "ProtectedAPI" it throttles again. So i will be trying after some time to see how much time it take to allow the requests again from the protected API. And if you want any more test to be done on Mac i would be happy to help!
![Screenshot 2021-06-04 at 3 38 59 PM](https://user-images.githubusercontent.com/59678544/120785684-fd214580-c54a-11eb-892e-2a27d46c41e8.png)

**Comment by aman-3003** [comment]
Try 2: After 15 min the ProtectedAPI is still throttling. 
![Screenshot 2021-06-04 at 3 56 33 PM](https://user-images.githubusercontent.com/59678544/120787877-70c45200-c54d-11eb-8db5-47b6346634d4.png)

**Comment by aman-3003** [comment]
Can we make requests from PublicAPI and if a slot is found then it tries to book from ProtectedAPI could that be done? @SRvSaha

**Comment by aman-3003** [comment]
Try 3: After 30 min when a single pin-code was searched it worked till try-20. Then i added 1 more pin-code it immediately throttled after 12 tries. But i think i found a workaround when it throttles if you just delete the authToken.json and ask for a new OTP then it again works for 20 tries before it throttles again. You can also automate the input of OTP using the methods used in this repo : https://github.com/bombardier-gif/covid-vaccine-booking 
![Screenshot 2021-06-04 at 4 20 05 PM](https://user-images.githubusercontent.com/59678544/120791206-876ca800-c551-11eb-9ba4-c3049202f4b6.png)

**Comment by SRvSaha** [comment]
> 
> 
> Can we make requests from PublicAPI and if a slot is found then it tries to book from ProtectedAPI could that be done? @SRvSaha

Yes right, that's what is the plan now. Please check #79 last comment.

**Comment by SRvSaha** [comment]
> 
> 
> Try 3: After 30 min when a single pin-code was searched it worked till try-20. Then i added 1 more pin-code it immediately throttled after 12 tries. But i think i found a workaround when it throttles if you just delete the authToken.json and ask for a new OTP then it again works for 20 tries before it throttles again. You can also automate the input of OTP using the methods used in this repo : https://github.com/bombardier-gif/covid-vaccine-booking
> ![Screenshot 2021-06-04 at 4 20 05 PM](https://user-images.githubusercontent.com/59678544/120791206-876ca800-c551-11eb-9ba4-c3049202f4b6.png)

Yes exactly right! That' what it is! This is what I am trying to do automated. The throttling message is coming because status code 403 is being returned. However it might not be throttling, it might be the Explicit Deny, Hence re-login would be needed. Since you are deleting authtoken file, essentially it is trying to do the same thing I am trying to automate. Good observation and proof. And yeah, thanks for you help with testing in Mac. Would need more support thanks.

**Comment by SRvSaha** [comment]
> 
> 
> Try 2: After 15 min the ProtectedAPI is still throttling.
> ![Screenshot 2021-06-04 at 3 56 33 PM](https://user-images.githubusercontent.com/59678544/120787877-70c45200-c54d-11eb-8db5-47b6346634d4.png)
It might not be throttling, can be just that they're sending explicit deny with 403 for the same login, So it works when you delete the token

**Comment by aman-3003** [comment]
> > Try 3: After 30 min when a single pin-code was searched it worked till try-20. Then i added 1 more pin-code it immediately throttled after 12 tries. But i think i found a workaround when it throttles if you just delete the authToken.json and ask for a new OTP then it again works for 20 tries before it throttles again. You can also automate the input of OTP using the methods used in this repo : https://github.com/bombardier-gif/covid-vaccine-booking
> > ![Screenshot 2021-06-04 at 4 20 05 PM](https://user-images.githubusercontent.com/59678544/120791206-876ca800-c551-11eb-9ba4-c3049202f4b6.png)
> 
> Yes exactly right! That' what it is! This is what I am trying to do automated. The throttling message is coming because status code 403 is being returned. However it might not be throttling, it might be the Explicit Deny, Hence re-login would be needed. Since you are deleting authtoken file, essentially it is trying to do the same thing I am trying to automate. Good observation and proof. And yeah, thanks for you help with testing in Mac. Would need more support thanks.

Would be happy to help ask me whenever you need some testing done on mac. And see the repo i mentioned it also does automated OTP's so users don't have to manually enter the OTP received. 👍🏻

**Comment by SRvSaha** [comment]
> 
> 
> > > Try 3: After 30 min when a single pin-code was searched it worked till try-20. Then i added 1 more pin-code it immediately throttled after 12 tries. But i think i found a workaround when it throttles if you just delete the authToken.json and ask for a new OTP then it again works for 20 tries before it throttles again. You can also automate the input of OTP using the methods used in this repo : https://github.com/bombardier-gif/covid-vaccine-booking
> > > ![Screenshot 2021-06-04 at 4 20 05 PM](https://user-images.githubusercontent.com/59678544/120791206-876ca800-c551-11eb-9ba4-c3049202f4b6.png)
> > 
> > 
> > Yes exactly right! That' what it is! This is what I am trying to do automated. The throttling message is coming because status code 403 is being returned. However it might not be throttling, it might be the Explicit Deny, Hence re-login would be needed. Since you are deleting authtoken file, essentially it is trying to do the same thing I am trying to automate. Good observation and proof. And yeah, thanks for you help with testing in Mac. Would need more support thanks.
> 
> Would be happy to help ask me whenever you need some testing done on mac. And see the repo i mentioned it also does automated OTP's so users don't have to manually enter the OTP received. 👍🏻

Regarding the Auto OTP: Actually I am procastinating it due to privacy concerns. Usually we don't collect any of the user data. Now, I see the core requirements are the followings for Auto-OTP:
1. Should be having very low latency and the service should be always available. Now most cloud providers do support it like KVDB but then the data is stored with them and there is issue with KVDB Buckets as anyone can delete it. Need some better service or a self developed service.
2. It would be best if there can be a local server which can be accessed if both the phone and the computer running the program are in same network. In that way we reduce latency quite a lot and thereby quick response.
3. Any other sugestions welcome.

**Comment by aman-3003** [comment]
> > > > Try 3: After 30 min when a single pin-code was searched it worked till try-20. Then i added 1 more pin-code it immediately throttled after 12 tries. But i think i found a workaround when it throttles if you just delete the authToken.json and ask for a new OTP then it again works for 20 tries before it throttles again. You can also automate the input of OTP using the methods used in this repo : https://github.com/bombardier-gif/covid-vaccine-booking
> > > > ![Screenshot 2021-06-04 at 4 20 05 PM](https://user-images.githubusercontent.com/59678544/120791206-876ca800-c551-11eb-9ba4-c3049202f4b6.png)
> > > 
> > > 
> > > Yes exactly right! That' what it is! This is what I am trying to do automated. The throttling message is coming because status code 403 is being returned. However it might not be throttling, it might be the Explicit Deny, Hence re-login would be needed. Since you are deleting authtoken file, essentially it is trying to do the same thing I am trying to automate. Good observation and proof. And yeah, thanks for you help with testing in Mac. Would need more support thanks.
> > 
> > 
> > Would be happy to help ask me whenever you need some testing done on mac. And see the repo i mentioned it also does automated OTP's so users don't have to manually enter the OTP received. 👍🏻
> 
> Regarding the Auto OTP: Actually I am procastinating it due to privacy concerns. Usually we don't collect any of the user data. Now, I see the core requirements are the followings for Auto-OTP:
> 
> 1. Should be having very low latency and the service should be always available. Now most cloud providers do support it like KVDB but then the data is stored with them and there is issue with KVDB Buckets as anyone can delete it. Need some better service or a self developed service.
> 2. It would be best if there can be a local server which can be accessed if both the phone and the computer running the program are in same network. In that way we reduce latency quite a lot and thereby quick response.
> 3. Any other sugestions welcome.

Yess that's the thing either people can create their own bucket. The idea of local server is also cool. If i can any other alternative will tell you.

**Comment by SRvSaha** [comment]
@aman-3003 Version 5.2.0 is out now will all the fixes suggested here and #79 along with new features for better UX. Thank you for your patience and support. Check it out and share your feedback!

**Comment by SRvSaha** [comment]
> 
> 
> > > Try 3: After 30 min when a single pin-code was searched it worked till try-20. Then i added 1 more pin-code it immediately throttled after 12 tries. But i think i found a workaround when it throttles if you just delete the authToken.json and ask for a new OTP then it again works for 20 tries before it throttles again. You can also automate the input of OTP using the methods used in this repo : https://github.com/bombardier-gif/covid-vaccine-booking
> > > ![Screenshot 2021-06-04 at 4 20 05 PM](https://user-images.githubusercontent.com/59678544/120791206-876ca800-c551-11eb-9ba4-c3049202f4b6.png)
> > 
> > 
> > Yes exactly right! That' what it is! This is what I am trying to do automated. The throttling message is coming because status code 403 is being returned. However it might not be throttling, it might be the Explicit Deny, Hence re-login would be needed. Since you are deleting authtoken file, essentially it is trying to do the same thing I am trying to automate. Good observation and proof. And yeah, thanks for you help with testing in Mac. Would need more support thanks.
> 
> Would be happy to help ask me whenever you need some testing done on mac. And see the repo i mentioned it also does automated OTP's so users don't have to manually enter the OTP received. 👍🏻

Hi @amn-3003 Can you please test the v5.2.0 in Mac and see if it works? Also, can you create a step by step procedure how to run it on mac, to be added in ReadMe

**Comment by aman-3003** [comment]
> > > > Try 3: After 30 min when a single pin-code was searched it worked till try-20. Then i added 1 more pin-code it immediately throttled after 12 tries. But i think i found a workaround when it throttles if you just delete the authToken.json and ask for a new OTP then it again works for 20 tries before it throttles again. You can also automate the input of OTP using the methods used in this repo : https://github.com/bombardier-gif/covid-vaccine-booking
> > > > ![Screenshot 2021-06-04 at 4 20 05 PM](https://user-images.githubusercontent.com/59678544/120791206-876ca800-c551-11eb-9ba4-c3049202f4b6.png)
> > > 
> > > 
> > > Yes exactly right! That' what it is! This is what I am trying to do automated. The throttling message is coming because status code 403 is being returned. However it might not be throttling, it might be the Explicit Deny, Hence re-login would be needed. Since you are deleting authtoken file, essentially it is trying to do the same thing I am trying to automate. Good observation and proof. And yeah, thanks for you help with testing in Mac. Would need more support thanks.
> > 
> > 
> > Would be happy to help ask me whenever you need some testing done on mac. And see the repo i mentioned it also does automated OTP's so users don't have to manually enter the OTP received. 👍🏻
> 
> Hi @amn-3003 Can you please test the v5.2.0 in Mac and see if it works? Also, can you create a step by step procedure how to run it on mac, to be added in ReadMe

It works great! I have created a pull request 👍🏻
