### ISSUE TITLE
Showing SECOND DOSE slot even though type 1 selected.

### ISSUE THREAD

**Issue by Tnu02** [SRvSaha/CoWinVaccineSlotFinder#76]
not sure why even thou type 1 dose is set, it showed and tried to book for SECOND DOSE ( althou it failed) but ideally it should haven't happened.

What your thoughts @SRvSaha

**Comment by SRvSaha** [comment]
Share the Config, it shouldn't have happened.

**Comment by Tnu02** [comment]
> Share the Config, it shouldn't have happened. Tried to replicate, couldn't see the bug. Do you have any screenshots?

Sharing the same...

Please check @SRvSaha 

![2nd Dose](https://user-images.githubusercontent.com/83922100/120344079-e2668b00-c316-11eb-9bbd-841a1f0ef675.PNG)
![2nd Dose Count](https://user-images.githubusercontent.com/83922100/120344086-e4304e80-c316-11eb-9f17-e1f9f13bf1d4.jpg)

**Comment by Tnu02** [comment]
Also we need to take care for this execption, atleast it should not break or close the app instead it should wait for the next ip or something.
![Exception](https://user-images.githubusercontent.com/83922100/120344487-412c0480-c317-11eb-9946-424874b616b8.jpg)

**Comment by SRvSaha** [comment]
> 
> 
> Also we need to take care for this execption, atleast it should not break or close the app instead it should wait for the next ip or something.
> ![Exception](https://user-images.githubusercontent.com/83922100/120344487-412c0480-c317-11eb-9946-424874b616b8.jpg)

This will be a part for v5.0.1 releasing tonight

**Comment by SRvSaha** [comment]
> 
> 
> > Share the Config, it shouldn't have happened. Tried to replicate, couldn't see the bug. Do you have any screenshots?
> 
> Sharing the same...
> 
> Please check @SRvSaha
> 
> ![2nd Dose](https://user-images.githubusercontent.com/83922100/120344079-e2668b00-c316-11eb-9bbd-841a1f0ef675.PNG)
> ![2nd Dose Count](https://user-images.githubusercontent.com/83922100/120344086-e4304e80-c316-11eb-9f17-e1f9f13bf1d4.jpg)

I think I have found the bug. Basically, it is taking correctly the vaccine available capacity of 1st Dose only but it is showing wrongly as SECOND Dose.

Just to confirm my doubt, please share the `MinimumVaccineAvailability` from config. Once I check that, I will be sure and it will be fixed in v5.0.1

**Comment by SRvSaha** [comment]
> 
> 
> > `MinimumVaccineAvailability`
> 
> That's correct.. @SRvSaha
> 
> MinimumVaccineAvailability was set to 2

Okay cool. My hunch was correct. Thanks for bringing this to notice. Shall be fixed and released tonight

**Comment by Tnu02** [comment]
> > 
> > 
> > > `MinimumVaccineAvailability`
> > 
> > That's correct.. @SRvSaha
> > 
> > MinimumVaccineAvailability was set to 2
> 
> Okay cool. My hunch was correct. Thanks for bringing this to notice. Shall be fixed and released tonight

Nice.. Looking forward to it.. Waiting.. 😊

**Comment by SRvSaha** [comment]
@Tnu02 v5.1.0 is now up and running! Check it out and share your feedback. Share in your circles:
Windows: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.1.0-windows
MacOSX: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.1.0-osx
Linux: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.1.0-linux
