### ISSUE TITLE
Not able to book slot using 5.1

### ISSUE THREAD

**Issue by Tnu02** [SRvSaha/CoWinVaccineSlotFinder#77]
![5 1](https://user-images.githubusercontent.com/83922100/120479104-2e730780-c3cb-11eb-828a-d109f5246da4.jpg)

@SRvSaha  though it is showing slot but didn't book any.. Can you please check.

**Comment by SRvSaha** [comment]
@Tnu02 Seems like a concurrency issue. From the time slots were visible and till booking, all 105 slots got booked. Though it is highly unlikely. Seems like the data being shown from CoWIN API is delayed hence the issue is being faced. Shall have to check,

**Comment by 520rahul** [comment]
> ![5 1](https://user-images.githubusercontent.com/83922100/120479104-2e730780-c3cb-11eb-828a-d109f5246da4.jpg)
> 
> @SRvSaha though it is showing slot but didn't book any.. Can you please check.

@Tnu02 what is your sleep intervel rate

**Comment by Tnu02** [comment]
> > ![5 1](https://user-images.githubusercontent.com/83922100/120479104-2e730780-c3cb-11eb-828a-d109f5246da4.jpg)
> > 
> > @SRvSaha though it is showing slot but didn't book any.. Can you please check.
> 
> @Tnu02 what is your sleep intervel rate

3500 for single pin code

**Comment by SRvSaha** [comment]
@Tnu02 If you know the exact timing when slots are gonna open, or else you get some real-time notification from somewhere, just drop the Sleep Interval to 1000 and then try. This would block your IP sonner but you have higher change of getting the slot.
Also, you may less the RefreshInterval to 2 seconds.

**Comment by 520rahul** [comment]
> @Tnu02 If you know the exact timing when slots are gonna open, or else you get some real-time notification from somewhere, just drop the Sleep Interval to 1000 and then try. This would block your IP sonner but you have higher change of getting the slot.
> Also, you may less the RefreshInterval to 2 seconds.

@SRvSaha is there some option like refresh ip address

**Comment by Tnu02** [comment]
Sometime I get error fetch slot error responsestatus: no content, response content.. What does it mean..?!??

**Comment by SRvSaha** [comment]
> 
> 
> Sometime I get error fetch slot error responsestatus: no content, response content.. What does it mean..?!??

First possibility, Internet Connectivity Issue so unable to reach the server. Second possiblilty, API timed out or

**Comment by Tnu02** [comment]
> > Sometime I get error fetch slot error responsestatus: no content, response content.. What does it mean..?!??
> 
> First possibility, Internet Connectivity Issue so unable to reach the server. Second possiblilty, API timed out or

And what about this error...
![Error](https://user-images.githubusercontent.com/83922100/120485204-7eed6380-c3d1-11eb-9ecf-290a3fb447a6.jpg)

**Comment by SRvSaha** [comment]
> > > Sometime I get error fetch slot error responsestatus: no content, response content.. What does it mean..?!??
> > 
> > 
> > First possibility, Internet Connectivity Issue so unable to reach the server. Second possiblilty, API timed out or
> 
> And what about this error...
> ![Error](https://user-images.githubusercontent.com/83922100/120485204-7eed6380-c3d1-11eb-9ecf-290a3fb447a6.jpg)

It’s there in README. Check it out!

**Comment by Tnu02** [comment]
@SRvSaha Hey.. Just a thought.. Is it possible to accept the license once in a session just to speed up execution at the time of slot opening..

**Comment by SRvSaha** [comment]
@Tnu02 That’s not needed since you don’t have to close application when IP is throttled. If you want less theottling time, you can change that in the config accordingly! And agreement to the T&C is a must and there should not be any by-pass else people misuses it!

**Comment by SRvSaha** [comment]
> @Tnu02 If you know the exact timing when slots are gonna open, or else you get some real-time notification from somewhere, just drop the Sleep Interval to 1000 and then try. This would block your IP sonner but you have higher change of getting the slot.
> Also, you may less the RefreshInterval to 2 seconds.

@Tnu02 Lisence doesn’t affect youe booking time, this does! Read this!

**Comment by Tnu02** [comment]
> > @Tnu02 If you know the exact timing when slots are gonna open, or else you get some real-time notification from somewhere, just drop the Sleep Interval to 1000 and then try. This would block your IP sonner but you have higher change of getting the slot.
> > Also, you may less the RefreshInterval to 2 seconds.
> 
> @Tnu02 Lisence doesn’t affect youe booking time, this does! Read this! 

It slows down the action i mean after pressing y and enter takes a couple of sec to start searching slot...
