### ISSUE TITLE
Rate limit on mobile no also

### ISSUE THREAD

**Issue by 520rahul** [SRvSaha/CoWinVaccineSlotFinder#78]
@SRvSaha now cowin has put rate limit on mobile no login also.  If ur call exceeds 20 per minute it blocks ur ip even u change ip bcoz it has blocked mobile no also for some time.

**Comment by SRvSaha** [comment]
@520rahul Yeah seems like they have added this new check today. I have added #79 which had details. Please test it and share your feedback. Accordingly we need to check out some alternative.

**Comment by 520rahul** [comment]
@SRvSaha 🙏🏻 Thanks for quite quick response. I m gonna try this.

**Comment by 520rahul** [comment]
![112D8C6B-E349-4C2F-8539-3AFCD2E165DE](https://user-images.githubusercontent.com/85031100/120685866-fbf60700-c4bd-11eb-83db-868402fa2c76.jpeg)


@SRvSaha workaround is not working.  After entering otp many times still not able to search for slot and this error comes everytime.  Plz have a look. U r the only hope

**Comment by SRvSaha** [comment]
@520rahul Please follow the description in #79 As others have reported, the steps work! Let me know your feedback
