### ISSUE TITLE
District Codes

### ISSUE THREAD

**Issue by 5HU8H** [SRvSaha/CoWinVaccineSlotFinder#8]
Where to get the district codes from?

**Comment by 5HU8H** [comment]
Thanks a ton!

**Comment by SRvSaha** [comment]
@PSuyog97 Please create district wise mapping for each state in JSON format (Key: Value for "DistrictName" : "DistrictId") and save it in data and mention it in the ReadMe

**Comment by SRvSaha** [comment]
@anisingh62  For 45+ Keep Min Age As 45 and Max As 100.

Star the Repo if it helps!

**Comment by AkulRastogi** [comment]
#20 Added the district codes in a markdown file. Sorted by state and district names.
