### ISSUE TITLE
It is not searching all centres

### ISSUE THREAD

**Issue by 9Jbl9** [SRvSaha/CoWinVaccineSlotFinder#82]
When we search by pincode such as "400016", "400053", "400068" (P D Hinduja 1, KOKILABEN HOSPITAL 1
<img width="680" alt="Screenshot 2021-06-07 at 4 27 15 PM" src="https://user-images.githubusercontent.com/85490839/121005528-8cc62e80-c7ad-11eb-9175-fbad089fa57f.png">
<img width="759" alt="Screenshot 2021-06-07 at 4 26 36 PM" src="https://user-images.githubusercontent.com/85490839/121005544-9059b580-c7ad-11eb-8985-ae7c38a2d1bb.png">

<img width="1195" alt="Screenshot 2021-06-07 at 4 33 48 PM" src="https://user-images.githubusercontent.com/85490839/121006361-7076c180-c7ae-11eb-9b4a-c41d759e12a4.png">

it is not displaying the centre, but when we go and search on self registration website there centres are displayed.

**Comment by SRvSaha** [comment]
Hi @9Jbl9, by default it searches for the next day which in your case is 08-06-2021. Also. Based on your screenshots, check that for 18-45 there are no availability for your dose type on the date. Please re-check

**Comment by 9Jbl9** [comment]
Hi SRvSaha,

Thanks for your reply.
My search conditions are as follows 
Pin code: 400016 & 400053
Vaccination Type: Covaxin
Fee: Free
According to me the output should be no center, but it showing lot of centers.
Please have a look on the screenshot for analyses.

<img width="1435" alt="1" src="https://user-images.githubusercontent.com/85490839/121042510-631efe80-c7d1-11eb-9c72-9ea609f85ad9.png">
<img width="1102" alt="2" src="https://user-images.githubusercontent.com/85490839/121042552-6d40fd00-c7d1-11eb-8fa6-5dfdb158cfb6.png">
<img width="1138" alt="3" src="https://user-images.githubusercontent.com/85490839/121042643-82b62700-c7d1-11eb-8801-3af293fa131c.png">
<img width="1141" alt="4" src="https://user-images.githubusercontent.com/85490839/121042687-8d70bc00-c7d1-11eb-90ab-82a985891e0c.png">
<img width="1131" alt="5" src="https://user-images.githubusercontent.com/85490839/121042725-96fa2400-c7d1-11eb-90c0-35d4718c2143.png">
<img width="1129" alt="6" src="https://user-images.githubusercontent.com/85490839/121042768-9feaf580-c7d1-11eb-9d25-41db49c81acd.png">
<img width="1135" alt="7" src="https://user-images.githubusercontent.com/85490839/121042814-a9745d80-c7d1-11eb-8ecd-c7b8da9e19e9.png">

Please suggest if am doing something wrong.

**Comment by 9Jbl9** [comment]
Hi SRvSaha,

Another scenario which is also not working.
Pin code: 401107 & 401101
Vaccination Type: Covaxin
Fee: “” (means any Paid or Free)

According to me the output should be no center, but it showing one center which is vaccinating elderly person (45).

I personally feel it is not satisfying “Vaccine Type” and “Fee”
Please have a look on the screenshot for analyses.

<img width="1443" alt="1A" src="https://user-images.githubusercontent.com/85490839/121053447-00316580-c7d9-11eb-9d33-dccd3239b4b3.png">

<img width="1111" alt="2a" src="https://user-images.githubusercontent.com/85490839/121053479-0aebfa80-c7d9-11eb-9433-80e2536569dd.png">

<img width="988" alt="3a" src="https://user-images.githubusercontent.com/85490839/121053522-15a68f80-c7d9-11eb-8ff2-8b257ef7830e.png">

**Comment by SRvSaha** [comment]
Hi @9Jbl9 I will check that out. Meanwhile you can check out this: Version 5.2.0 is out now will all the fixes suggested here and #79 along with new features for better UX. Check it out and share your feedback!

**Comment by SRvSaha** [comment]
> 
> 
> Hi SRvSaha,
> 
> Another scenario which is also not working.
> Pin code: 401107 & 401101
> Vaccination Type: Covaxin
> Fee: “” (means any Paid or Free)
> 
> According to me the output should be no center, but it showing one center which is vaccinating elderly person (45).
> 
> I personally feel it is not satisfying “Vaccine Type” and “Fee”
> Please have a look on the screenshot for analyses.
> 
> <img alt="1A" width="1443" src="https://user-images.githubusercontent.com/85490839/121053447-00316580-c7d9-11eb-9d33-dccd3239b4b3.png">
> 
> <img alt="2a" width="1111" src="https://user-images.githubusercontent.com/85490839/121053479-0aebfa80-c7d9-11eb-9433-80e2536569dd.png">
> 
> <img alt="3a" width="988" src="https://user-images.githubusercontent.com/85490839/121053522-15a68f80-c7d9-11eb-8ff2-8b257ef7830e.png">

The scenario is correct and result is as excepted. Since you have given Age Range of 18-44, it is unable to find the match. But the Vaccination Centre was  found so, it is saying it was found but didn't match your criteria

**Comment by SRvSaha** [comment]
@9Jbl9 Hi, let me know if you could book. Else we can closed the issue

**Comment by 520rahul** [comment]
@SRvSaha it worked like a charm. I was able to book 3 slots of neighbours who were trying for more then a month to get a slot. Got their blessings.  Thank us so much boss. U rock. God bless u bcoz of u only i was able to book slots. Thanks a ton.  🙏🏻🙏🏻🙏🏻🙏🏻

**Comment by 9Jbl9** [comment]
Hi, SRVSaha,

Sorry I am busy with something. We can close.

Thanks once again.
