### ISSUE TITLE
New feature Minimum booking if slot available less then no of beneficiary  

### ISSUE THREAD

**Issue by betagoyal** [SRvSaha/CoWinVaccineSlotFinder#83]
No booking made if No. of available slots are less than no of the beneficiary.
There should be an option for minimum booking like if one slot available the first beneficiary gets that

**Comment by SRvSaha** [comment]
@betagoyal I thought of this earlier but there are some ifs and buts for this: Usually when someone is trying to do booking for multiple-beneficiaries, they usually want to do so cause they want all the beneficiaries can visit the Vaccination Centre together and get the job done. Otherwise if they are not bothered with doing separately, then it can be done now as well from the Application in multiple times with different different configs. So I don't see much value addition. You can share your comments.

**Comment by betagoyal** [comment]
sometimes... trying start after peak time and find only one slot and after some minutes another one. Think about it .

**Comment by SRvSaha** [comment]
@betagoyal I understand the requirement. It’s true that this ia a problem. However the new feature also won’t help. I will give you a scenario: Let’s say you were trying to book for 3 beneficiaries and the booking didn’t go through as Maybe only two slots available but then again you close the application and try with two beneficiaries it will go through now considered the scenario that I do automation in the app that takes a minimum beneficiary count and then it automatically takes the minimum number of beneficiaries and go but then again if this is there still you need to remove the beneficiary which has been booked and then for the remaining ones you need to run so I do not see much of a difference

**Comment by betagoyal** [comment]
Ok, I do agree with you. we can think about it. and yes the benefit is we have booked 2 slots in your scenario

**Comment by betagoyal** [comment]
ok, we can do one thing booking always one by one or booking all in one.

**Comment by SRvSaha** [comment]
> ok, we can do one thing booking always one by one or booking all in one.

One by one is an option! But that means multiple API calls. When stringent rate limit gets imposed, it will start failing.

**Comment by betagoyal** [comment]
> > ok, we can do one thing booking always one by one or booking all in one.
> 
> One by one is an option! But that means multiple API calls. When stringent rate limit gets imposed, it will start failing.

it will be optional so more chances

**Comment by SRvSaha** [comment]
@betagoyal You can keep `MinimumVaccineAvailability`: 3 in case you have 3 beneficiaries. Problem is solved using the current App only. So whenever 3 are available, it'll book. Else not.
