### ISSUE TITLE
How to compile for linux

### ISSUE THREAD

**Issue by deepgandhi** [SRvSaha/CoWinVaccineSlotFinder#87]
I would like to compile for aarch64 architecture so that it can be run on android with use of termux. How to compile in Linux @SRvSaha ?

**Comment by SRvSaha** [comment]
@deepgandhi I doubt that Termux has support for .NET Core Runtime. I wanted to do that but found it's not officially supported yet.

- https://github.com/termux/termux-packages/issues/516
- https://www.reddit.com/r/dotnet/comments/8f7igw/net_core_on_android/

If you want to build the project, you can use `dotnet build` command in the project where .csproj file is there for Core Project.
*.NET Core 3.1 SDK must be present in your system where you are building*.
To run, you can use `dotnet run` command. To package it, you can use follow these steps: https://docs.microsoft.com/en-us/dotnet/core/deploying/

Try to run the current linux 64 bit version in android and see if it works. There is another option of linux-arm. But I am not sure it it will work. 

It's more of an experimental thing.

**Comment by deepgandhi** [comment]
Actually, in my linux mint dotnet is not installed, still I was able to run it yesterday @SRvSaha. I think if it is compiled, there is no runtime requirements.

**Comment by SRvSaha** [comment]
> 
> 
> Actually, in my linux mint dotnet is not installed, still I was able to run it yesterday @SRvSaha. I think if it is compiled, there is no runtime requirements.

I have bundled the runtime requirements so that user doesn't fall in the dependency hell. I have made sure than Windows, Linux or MacOS Version works seamlessly either by one command running or by double clicking just.

**Comment by SRvSaha** [comment]
@deepgandhi Try running the current linux build in Android using Termux. Mostly probably it won't work, but let's see. Else I can provide you will a standalone linux-arm package to test using Termux.

**Comment by deepgandhi** [comment]
@SRvSaha yes, current version is not running. Actually I tied that first, but it didn't work so I asked you afterwards.

**Comment by SRvSaha** [comment]
@deepgandhi Since Termux doesn’t have native support for dotnet, it won’t work! So, closing thw issue
