### ISSUE TITLE
Cowin new terms and condition

### ISSUE THREAD

**Issue by 520rahul** [SRvSaha/CoWinVaccineSlotFinder#88]
https://www.cowin.gov.in/terms-condition

@SRvSaha plz have a look specially at point no. 3 and 4 . What is ur opinion

**Comment by SRvSaha** [comment]
Okay! Seems like the time has come to take the App down!

**Comment by 520rahul** [comment]
@SRvSaha boss if we keep our refresh rate within cowin terms range and send max call of 1000 per 24 hrs, can v use repo in that case or not, please enlighten.

**Comment by SRvSaha** [comment]
> 
> 
> @SRvSaha boss if we keep our refresh rate within cowin terms range and send max call of 1000 per 24 hrs, can v use repo in that case or not, please enlighten.

See it's tough to tell it is allowed on not. Basically unless you are bombarding their server with lots of requests, you may be allowed to use. As people are misusing it using OTP Automation and all, they have started blocking numbers as well. Till things are done in limit, there may not be any consequences. Switch `ProtectedAPI:IsToBeUsed`: false is my suggestion unless you find there you are missing on slots. That's better.

**Comment by 520rahul** [comment]
> > @SRvSaha boss if we keep our refresh rate within cowin terms range and send max call of 1000 per 24 hrs, can v use repo in that case or not, please enlighten.
> 
> See it's tough to tell it is allowed on not. Basically unless you are bombarding their server with lots of requests, you may be allowed to use. As people are misusing it using OTP Automation and all, they have started blocking numbers as well. Till things are done in limit, there may not be any consequences. Switch `ProtectedAPI:IsToBeUsed: false` is my suggestion unless you find there you are missing on slots. That's better. 1000 calls is possible roughly say when you know the timing when slot comes and follow Telegram Alerts of last 7 days. That'd give you idea, you can then use the App during that time only. [[Suggestion]]

Boss can u little bit elaborate that if v keep protected api as false then how v vill able to book slot. Can u explain the process to be followed assuming that v know the slot timing range.

**Comment by SRvSaha** [comment]
> 
> 
> > > @SRvSaha boss if we keep our refresh rate within cowin terms range and send max call of 1000 per 24 hrs, can v use repo in that case or not, please enlighten.
> > 
> > 
> > See it's tough to tell it is allowed on not. Basically unless you are bombarding their server with lots of requests, you may be allowed to use. As people are misusing it using OTP Automation and all, they have started blocking numbers as well. Till things are done in limit, there may not be any consequences. Switch `ProtectedAPI:IsToBeUsed: false` is my suggestion unless you find there you are missing on slots. That's better. 1000 calls is possible roughly say when you know the timing when slot comes and follow Telegram Alerts of last 7 days. That'd give you idea, you can then use the App during that time only. [[Suggestion]]
> 
> Boss can u little bit elaborate that if v keep protected api as false then how v vill able to book slot. Can u explain the process to be followed assuming that v know the slot timing range.

Don't worry, it is handled internally when we faced the last issue.

**Comment by 520rahul** [comment]
@SRvSaha u mean to say if v keep it as false it will search using findapi having limit of 100 calls/5 minutes, and if it finds a slot it will automatically shift to protected api and will book the slot.

**Comment by 520rahul** [comment]
![EA98DB6F-E522-4E87-B0D8-7B69708389C5](https://user-images.githubusercontent.com/85031100/121461892-59fa8100-c9cd-11eb-8d76-0bbda5bf6ea6.jpeg)


Todays TOI

**Comment by SRvSaha** [comment]
> 
> 
> Okay! Seems like the time has come to take the App down!

@520rahul @Tnu02 @betagoyal [UPDATE] Application is still up and running. Shall be up and functional until there is a hard requirement to take it down. However, to keep the activity in the repo low, I may keep it archived.
Demo, ReadMe, Latest Version of the software can be found here as well in case Github is down: https://shawt.io/r/sYK
In case you are still booking using it, just do it using some precautions. Don't bombard CoWIN Servers and don't be predictible. That's it. Thanks.

**Comment by 520rahul** [comment]
> > Okay! Seems like the time has come to take the App down!
> 
> @520rahul @Tnu02 @betagoyal [UPDATE] Application is still up and running. Shall be up and functional until there is a hard requirement to take it down. However, to keep the activity in the repo low, I may keep it archived.
> Demo, ReadMe, Latest Version of the software can be found here as well in case Github is down: https://shawt.io/r/sYK
> In case you are still booking using it, just do it using some precautions. Don't bombard CoWIN Servers and don't be predictible. That's it. Thanks.
> 
> > Don't Bombard CoWIN Servers with huge number of requests, if you are using the App, in that way you might be in trouble.
> > In case you are using it, use with precaution. You may get idea of openings of slots from historical data available here: https://under45.in/reports.php or from some alerts/notifications service like Telegram or by running this App (unless you are bombarding with 1/2 hours of searching for slots)

Thank u so much @SRvSaha  and have a great future ahead. And v hope u will keep us touching now and then. God bless u.
