### ISSUE TITLE
Help-Stopped running on my pc

### ISSUE THREAD

**Issue by 520rahul** [SRvSaha/CoWinVaccineSlotFinder#90]
@SRvSaha i just reinstalled windows 7 sp1 32 bit on my laptop today. To my surprise the repo has stopped  working on my laptop. As i click on exe file screen popup for 1 seconds and crashes.  I m using python 3.7.4 as it maximum supports my windows. Plz help

**Comment by 520rahul** [comment]
@SRvSaha 🙏🏻

**Comment by SRvSaha** [comment]
> @SRvSaha i just reinstalled windows 7 sp1 32 bit on my laptop today. To my surprise the repo has stopped working on my laptop. As i click on exe file screen popup for 1 seconds and crashes. I m using python 3.7.4 as it maximum supports my windows. Plz help

Hi @520rahul It doesn’t depend on Python Version. The .NET Core 3.1 Runtime is supported in Windows 7 SP 2 and higher. So, it’s not working.

Details here: https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=netcore31


I can only help if I get the information regarding crash. Follow the steps here #39 and share the Event Viewer details.

**Comment by SRvSaha** [comment]
> @SRvSaha 🙏🏻

What version of OS were you using earlier? Did you face any issues earlier?

**Comment by 520rahul** [comment]
> > @SRvSaha 🙏🏻
> 
> What version of OS were you using earlier? Did you face any issues earlier?

No earlier also i was using windows 7 ultimate only but no issue was faced.  But after installing win 7 ultimate  sp1 i faced the issue. I shall share my event log so that u can tell me the problem

**Comment by SRvSaha** [comment]
@520rahul Windows 7 SP1 is supported with Extended Security Updates installed.

Follow this and make sure the ESU is installed https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1-supported-os.md

**Comment by SRvSaha** [comment]
> 
> 
> > > @SRvSaha 🙏🏻
> > 
> > 
> > What version of OS were you using earlier? Did you face any issues earlier?
> 
> No earlier also i was using windows 7 ultimate only but no issue was faced. But after installing win 7 ultimate sp1 i faced the issue. I shall share my event log so that u can tell me the problem

Are you sure the earlier Windows 7 was also SP1? Make sure you read the dependencies required for using in Windows 7.
You can search how to use .NET Core 3.1 Runtime in Windows 7 SP1

**Comment by 520rahul** [comment]
> > > > @SRvSaha 🙏🏻
> > > 
> > > 
> > > What version of OS were you using earlier? Did you face any issues earlier?
> > 
> > 
> > No earlier also i was using windows 7 ultimate only but no issue was faced. But after installing win 7 ultimate sp1 i faced the issue. I shall share my event log so that u can tell me the problem
> 
> Are you sure the earlier Windows 7 was also SP1? Make sure you read the dependencies required for using in Windows 7.
> You can search how to use .NET Core 3.1 Runtime in Windows 7 SP1

No. My previous version was only windows 7 ultimate.  Do i need to reinstall that. Whether it will work

**Comment by SRvSaha** [comment]
> 
> 
> > > > > @SRvSaha 🙏🏻
> > > > 
> > > > 
> > > > What version of OS were you using earlier? Did you face any issues earlier?
> > > 
> > > 
> > > No earlier also i was using windows 7 ultimate only but no issue was faced. But after installing win 7 ultimate sp1 i faced the issue. I shall share my event log so that u can tell me the problem
> > 
> > 
> > Are you sure the earlier Windows 7 was also SP1? Make sure you read the dependencies required for using in Windows 7.
> > You can search how to use .NET Core 3.1 Runtime in Windows 7 SP1
> 
> No. My previous version was only windows 7 ultimate. Do i need to reinstall that. Whether it will work

If it was working earlier, it would continue to work. If you don't want to uninstall, install Virtual Box and then install either Windows 10 (which is free) inside it. It will work. Or else, if you are a bit familiar with Linux, you can install Ubuntu in the Virtual Box, it would be around 1GB of download and would work just fine. Otherwise you may install Windows 7 Ultimate > SP1. 
Even in SP1, it would work provided you have ensured that Extended Security Updates are installed.

Since Windows 7 is out of support now, even Microsoft won't support. Recommendation is to move to Windows 10 (which is free and lightweight).

**Comment by 520rahul** [comment]
@SRvSaha thank u sir. I shall update it to windows 10 and then i shall tell u results

**Comment by 520rahul** [comment]
@SRvSaha thanks brother.  I updated my windows now easily working on my windows. Thanks again
