### ISSUE TITLE
How to book a slot with a 13 digit beneficiary ID?

### ISSUE THREAD

**Issue by PanicusTotalus** [SRvSaha/CoWinVaccineSlotFinder#94]

**Comment by SRvSaha** [comment]
@PanicusTotalus You may use the [latest Release from here](https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.2.1-windows) in Windows which fixes the issue with 13 digit beneficiary ID.

Let me know if this works for you.

Linked Issue #93

**Comment by PanicusTotalus** [comment]
It works! Thank you for doing God's work and helping us help people.

**Comment by SRvSaha** [comment]
Awesome! @PanicusTotalus Happy to Help! Feel free to star the repo and share it in your circle. Let us know if you could book successfully! Closing the issue
