### ISSUE TITLE
Getting latest version available banner even if on 5.2.1

### ISSUE THREAD

**Issue by Tnu02** [SRvSaha/CoWinVaccineSlotFinder#95]
@SRvSaha I am getting new version banner even if I am on 5.2.1. Please check

**Comment by SRvSaha** [comment]
@Tnu02 Issue addressed with [Release v5.2.2](https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.2.2-windows)
Please check and inform if it is working properly for both #93 and #95!
