### ISSUE TITLE
Change in age

### ISSUE THREAD

**Issue by Tnu02** [SRvSaha/CoWinVaccineSlotFinder#96]
It seems cowin again changed the booking UI for some state like they changed it 18+ & above and removed 45+. I haven't checked with the latest version but would be wondering whether it will working in this scenario or we need to modify anything. Any comment @SRvSaha 
![Above](https://user-images.githubusercontent.com/83922100/124351817-2997b280-dc1a-11eb-8f69-1fb3d409c9bd.PNG)

**Comment by SRvSaha** [comment]
@Tnu02 Our Application is configurable since it can use any Value from Max and Min age from appSettings.json So, I think it should work without any changes required! Do check and let me know, in case it doesn’t
