### ISSUE TITLE
Multiple Slot Booking Query

### ISSUE THREAD

**Issue by PanicusTotalus** [SRvSaha/CoWinVaccineSlotFinder#99]
Is it possible to book slots for 2 different age groups (18-44 and 45+) at the same time using a single script if both the beneficiaries are registered on the same mobile number?

**Comment by SRvSaha** [comment]
> If you're selecting multiple beneficiaries, make sure all are of the same age group (45+ or 18+) as defined by the govt. Please do not try to club together booking for younger and older beneficiaries.

This used to be the scenario. Now since 18+ in includes 45+ as well if MinAgeLimit = 18 and MaxAgeLimit = 100, this MIGHT work!

But I am not sure! Try for yourself. Else try running two instances of Application with different different beneficiary ids. That’d work

**Comment by Tnu02** [comment]
@SRvSaha what if both the beneficiaries are of different dose.. like one is Type 1 and other is type 2. Would it be possible to book thru this.

**Comment by SRvSaha** [comment]
> Do NOT use unless all the beneficiaries selected are supposed to get the same vaccine and dose.
When multiple beneficiaries are added for a single registered mobile number, all beneficiaries will get the Same Dose, Same Vaccine, Same Centre and Same Slot. In case any of this doesn't meet the requirements, booking might not be successful.

@Tnu02 Not possible
